
 export const marketCategories = [
    'Work & Productivity Tools',
    'Marketing & Sales Tools',
    'Engineering & Development Tools',
    'AI Tools',
    'Design & Creative Tools',
    'No-Code & Low-Code Platforms',
    'Customer Support & Service Tools',
    'Data & Analytics Tools',
    'HR & People Operations Tools',
    'Finance & Accounting Tools',
    'Web3 & Blockchain Tools',
    'Product Add-ons & Integrations',
    'Industry-Specific SaaS',
  ] as const;

export type MarketCategory = (typeof marketCategories)[number];

  export const marketSubcategories: Record<MarketCategory, string[]> = {
    'Work & Productivity Tools': [
      'Project & Task Management',
      'Note-Taking & Knowledge Management',
      'Team Collaboration & Communication',
      'Email Clients & Management',
      'Calendar & Scheduling Software',
      'Meeting & Video Conferencing Software',
      'Virtual Office Platforms',
      'File Storage & Sharing Solutions',
      'Document Creation & Management',
      'E-Signature Solutions',
      'PDF Editors & Management',
      'Password Management',
      'Time Tracking Software',
      'Productivity Suites',
      'Writing Assistants',
      'Screen Recording & Screenshot Tools',
    ],
    'Marketing & Sales Tools': [
      'CRM',
      'Sales Automation & Outreach',
      'Lead Generation & Prospecting',
      'Marketing Automation Platforms',
      'Email Marketing Platforms',
      'SEO Tools',
      'Content Marketing Platforms',
      'Social Media Management & Scheduling',
      'Influencer Marketing Platforms',
      'Advertising & PPC Management Tools',
      'Affiliate Marketing Platforms',
      'Marketing Analytics & Attribution',
      'Conversion Rate Optimization Tools',
      'Landing Page Builders',
      'Survey & Form Builders',
      'Public Relations Software',
      'Sales Enablement Platforms',
      'Customer Loyalty & Referral Programs',
    ],
    'Engineering & Development Tools': [
      'Cloud Computing & Hosting Platforms',
      'DevOps & CI/CD Platforms',
      'Version Control & Code Collaboration',
      'Testing & QA Software',
      'API Management & Development Services',
      'Backend-as-a-Service & Frameworks',
      'Database Management Tools',
      'Monitoring & Observability Platforms',
      'Issue Tracking & Bug Reporting',
      'Code Editors & IDEs',
      'Authentication & Identity Management',
      'Static Site Generators',
      'Content Management Systems',
      'Headless CMS',
      'VPN Clients',
    ],
    'AI Tools': [
      'AI Chatbots & Virtual Assistants',
      'AI Generative Content',
      'AI Coding Assistants',
      'AI Data Analysis & Business Intelligence',
      'AI Notetakers & Transcription Services',
      'AI Content Detection & Verification',
      'AI Infrastructure & MLOps',
      'AI Voice Agents & Speech-to-Text/Text-to-Speech',
      'LLM Platforms & Prompt Engineering Tools',
      'Predictive Analytics & Machine Learning Platforms',
      'AI Search & Knowledge Discovery',
      'AI Personalization Engines',
    ],
    'Design & Creative Tools': [
      'Graphic Design Software',
      'Photo Editing & Management Software',
      'Video Editing & Hosting Platforms',
      'UI/UX Design & Prototyping Tools',
      'Wireframing & Mockup Tools',
      '3D Modeling & Animation Software',
      'Design Asset Management & Libraries',
      'Digital Whiteboards & Visual Collaboration',
      'User Research & Testing Platforms',
      'Presentation Design Software',
    ],
    'No-Code & Low-Code Platforms': [
      'No-Code/Low-Code Website Builders',
      'No-Code/Low-Code Web & Mobile App Builders',
      'No-Code/Low-Code Automation & Workflow Builders',
      'No-Code/Low-Code Form & Survey Builders',
      'No-Code/Low-Code Database & Backend Builders',
      'No-Code/Low-Code Chatbot Builders',
    ],
    'Customer Support & Service Tools': [
      'Helpdesk & Ticketing Systems',
      'Live Chat & Customer Messaging Platforms',
      'Knowledge Base & Self-Service Software',
      'Customer Feedback & Survey Tools',
      'Community Management Platforms',
      'Call Center Software',
      'Customer Success Platforms',
    ],
    'Data & Analytics Tools': [
      'Business Intelligence & Reporting Platforms',
      'Data Visualization Tools',
      'Web & Product Analytics Platforms',
      'A/B Testing & Experimentation Software',
      'Data Integration & ETL Tools',
      'Customer Data Platforms',
      'Data Warehouse Solutions',
      'Big Data Processing & Analytics',
    ],
    'HR & People Operations Tools': [
      'Applicant Tracking Systems & Recruiting Software',
      'Employee Onboarding & Offboarding Software',
      'Performance Management & Feedback Platforms',
      'HRIS',
      'Payroll & Benefits Administration Software',
      'Employee Engagement & Recognition Platforms',
      'Learning Management Systems',
      'Workforce Management & Scheduling',
    ],
    'Finance & Accounting Tools': [
      'Accounting & Bookkeeping Software',
      'Billing, Invoicing & Subscription Management',
      'Payment Processing & Gateway Solutions',
      'Expense Management Software',
      'Financial Planning & Analysis Software',
      'Budgeting & Forecasting Tools',
      'Tax Compliance & Preparation Software',
      'Treasury Management Systems',
      'Startup Financial Planning & Cap Table Management',
      'Fundraising & Investor Relations Platforms',
    ],
    'Web3 & Blockchain Tools': [
      'Crypto Payment Gateways & Processing',
      'NFT Creation & Marketplace Platforms',
      'DAO Management & Tooling',
      'Blockchain Development Platforms',
      'Smart Contract Auditing & Security',
      'Decentralized Identity Solutions',
      'Crypto Wallet Infrastructure',
    ],
    'Product Add-ons & Integrations': [
      'Browser Extensions',
      'Platform Plugins',
      'Application Connectors & Native Integrations',
      'Templates as a Product',
    ],
    'Industry-Specific SaaS': [
      'Healthcare & MedTech SaaS',
      'LegalTech SaaS',
      'Real Estate Tech SaaS',
      'EdTech SaaS',
      'Travel & Hospitality Tech SaaS',
      'E-commerce Platforms & Tools',
      'Fitness & Wellness Tech SaaS',
    ],
  };

  export const taxonomy = {

    marketCategories: [...marketCategories],
    marketSubcategories,
  landingGoals: [
    'Join Waitlist', 'Get Early Access', 'Sign Up for Beta', 'Request a Demo', 'Get a Free Trial',
    'Download Whitepaper', 'Access Case Study', 'Subscribe to Newsletter', 'Get Product Updates',
    'Sign Up for Webinar', 'Start Free Trial', 'Create Free Account', 'Buy Now', 'Subscribe to a Plan',
    'Upgrade Plan', 'Activate Account', 'Book a Call / Strategy Session', 'Install App / Extension',
    'Download App', 'Add to Slack / Discord / Chrome', 'Read More / Learn More', 'Watch Video / Product Tour',
    'Explore Features', 'Compare Plans', 'See Pricing', 'Read Documentation', 'Visit Help Center',
    'Contact Sales', 'Schedule a Call', 'Talk to an Expert', 'Chat with Support', 'Submit Inquiry',
    'Refer a Friend', 'Claim Offer / Discount', 'Redeem Coupon', 'Participate in Contest / Giveaway',
    'Submit Feedback', 'Join Community / Discord'
  ],

  targetAudiences: [
    'Early-Stage Founders', 'Solopreneurs', 'Startup Teams', 'Indie Hackers', 'Tech Founders',
    'Non-Tech Founders', 'Content Creators', 'YouTubers', 'Newsletter Writers', 'Podcasters',
    'Creator Economy Entrepreneurs', 'Growth Hackers', 'Performance Marketers', 'Product Marketers',
    'Fractional CMOs', 'Freelance Marketers', 'Marketing Agencies', 'Design Agencies', 'No-Code Agencies',
    'Early-Stage Startups', 'Small Businesses (SMBs)', 'D2C Brands', 'E-commerce Sellers', 'Local Service Providers',
    'Mid-Market Companies', 'Enterprise Tech Teams', 'Enterprise Marketing Teams', 'IT Decision Makers',
    'Developers', 'No-Code Builders', 'Product Managers', 'Startup CTOs', 'Online Educators', 'Course Creators',
    'Coaches & Consultants', 'Cohort-Based Instructors', 'Community Managers', 'Non-Profit Organizations'
  ],

  startupStages: [
    'Problem exploration (no product yet)', 'Pre-MVP (wireframes or prototype only)', 'MVP in development',
    'MVP launched, 0 users', 'First few users (<10)', 'Initial feedback phase (10–50 users)',
    'Problem–solution fit (50–100 users)', 'Validated with early adopters (100–250 users)',
    'Early monetization (first paying customers)', 'Building v2 based on feedback',
    'Improving activation & retention', '250–500 users', 'Targeting product–market fit',
    'First marketing experiments', 'Hiring first team members', '500–1000 users',
    'Defined ICP and go-to-market strategy', 'Preparing for pre-seed/seed fundraising', '1K–5K users',
    'Consistent MRR growth', 'Active sales & marketing team', 'Operational processes in place',
    'Seed or Series A funded', '5K–50K users', 'Series B or beyond', 'Scaling team & infrastructure',
    'Fully staffed marketing & product teams', 'Expanding into new markets', 'Churn reduction & LTV optimization',
    '50K+ users or ARR > $10M', 'Global presence or multi-product suite',
    'Strict compliance & security processes', 'Long sales cycles & high-touch onboarding',
    'Enterprise account management focus'
  ],

  pricingModels: [
    'Free', 'Freemium (limited features)', 'Free Trial (no credit card)', 'Free Trial (with credit card)',
    '$1 Trial / Paid Trial', 'Money-Back Guarantee', 'Pay After Use / Success-Based',
    'Flat Monthly Fee (<$20/month)', 'Flat Monthly Fee ($20–$50/month)', 'Flat Monthly Fee ($50–$200/month)',
    'Flat Monthly Fee ($200+/month)', 'Usage-Based Pricing', 'Tiered Pricing (Basic / Pro / Enterprise)',
    'Per Seat Pricing', 'Custom Quote / Talk to Sales', 'Annual Contract Required', 'Pricing Hidden (Request Access)'
  ]
};
