// src/modules/service/copy/copyPromptService.ts
// Copy generation prompt builder for the service route. Mirror of copyPromptV3
// but driven by ServiceStrategyOutput shape (oneClient/ourPosition) and the
// Hearth voice spec instead of vibe-based tone mapping.

import type {
  ServiceStrategyOutputAssembled,
  ServiceUnderstandingInput,
  ServiceGoal,
} from '@/types/service';
import {
  layoutElementSchema,
  getAllElements,
  getCardRequirements,
  type LayoutElement,
  type CardRequirements,
} from '@/modules/sections/layoutElementSchema';
import { formatServiceVoiceForPrompt } from './voice';
import { assertNoTemplateLeak } from './promptFirewall';
import { serviceGoalLabels } from '@/types/service';

export interface ServiceCopyPromptInput {
  strategy: ServiceStrategyOutputAssembled;
  uiblocks: Record<string, string>;
  oneLiner: string;
  businessName?: string;
  offer: string;
  goal: ServiceGoal;
  understanding: ServiceUnderstandingInput;
}

function formatElement(element: LayoutElement): string {
  const parts: string[] = [`- ${element.element}`];
  if (element.charLimit) parts.push(`(max ${element.charLimit} chars)`);
  parts.push(element.mandatory ? '[REQUIRED]' : '[optional, null to exclude]');
  if (element.generation === 'ai_generated_needs_review') parts.push('[NEEDS_REVIEW]');
  return parts.join(' ');
}

function formatCardRequirements(req: CardRequirements | null): string {
  if (!req) return '';
  return `Items: min ${req.min}, max ${req.max}`;
}

function getAIElements(layoutName: string): LayoutElement[] {
  const schema = layoutElementSchema[layoutName];
  if (!schema) return [];
  return getAllElements(schema).filter(
    (e) => e.generation === 'ai_generated' || e.generation === 'ai_generated_needs_review'
  );
}

function buildSectionSpec(sectionType: string, layoutName: string): string {
  const schema = layoutElementSchema[layoutName];
  if (!schema) return `### ${sectionType} (${layoutName})\nNo schema available`;

  const elements = getAIElements(layoutName);
  const cardReq = getCardRequirements(schema);

  const lines: string[] = [`### ${sectionType} (${layoutName})`];
  if (cardReq) lines.push(formatCardRequirements(cardReq));
  lines.push('Elements:');
  for (const el of elements) lines.push(formatElement(el));
  return lines.join('\n');
}

/**
 * Goal-specific CTA guidance — steers the verbs/commitment level of every
 * CTA-bearing field (header.cta_text, hero.cta_text, packages[].cta_text,
 * cta.cta_text). CTA variation is copy-level on the shared BookCallCTA block —
 * there is no per-goal CTA block (Phase 9 hold).
 */
function getGoalCtaGuidance(goal: ServiceGoal): string {
  const map: Partial<Record<ServiceGoal, string>> = {
    'book-call':
      'Goal = book a call. CTA copy should invite a low-pressure conversation: "Book a call", "Book a discovery call", "Start a conversation". Warm, no hard sell.',
    'request-quote':
      'Goal = request a quote. CTA copy should invite a scoped, custom estimate: "Request a quote", "Get a quote", "Scope your project". Signal bespoke pricing, not a fixed price tag.',
    'lead-magnet':
      'Goal = lead magnet. CTA copy should offer the free resource with minimal commitment: "Get the guide", "Download the resource", "Send it to me". Make the value of the resource obvious; do NOT imply a sales call.',
  };
  return map[goal] ?? map['book-call']!;
}

function getEmotionalContext(awareness: string): string {
  const map: Record<string, string> = {
    'search-aware-cold':      'Visitor Googled the service category. Has a need but no preferred provider yet — they need to feel "this provider gets it" within 3 seconds.',
    'search-aware-comparing': 'Visitor is shopping multiple providers. Has multiple tabs open. Differentiation must be sharp; trust signals must come early.',
    'referral-driven':        'Visitor came from a recommendation — name pre-trusted, but they\'re scanning to confirm fit before booking.',
    'relationship-warming':   'Visitor knew the founder personally. Deciding whether to engage commercially. Voice should feel familiar, not pitchy.',
  };
  return map[awareness] ?? 'Visitor is exploring options.';
}

/**
 * Element schemas for collections (helps LLM emit the right shape per array).
 */
function getElementSchemas(): string {
  return `
Collection schemas (for array fields):
- nav_items: array of { id: string, label: string, href: string }
- services: array of { id: string, title: string, description: string, icon: string, cta_text: string }
- packages: array of { id: string, name: string, price_display: string [NEEDS_REVIEW], timeline: string, features: string[], cta_text: string, is_featured: boolean }
- social_links: array of { id: string, platform: string, href: string }

Notes:
- "id" fields are auto-generated by the system — emit empty string or omit; do NOT invent IDs.
- price_display: For pilot, use ranges or "from $X" framing. NEEDS_REVIEW: founder will verify before publish. Avoid invented exact numbers.
- features (in packages): 4-7 short phrases, concrete deliverables.`;
}

export function buildServiceCopyPrompt(input: ServiceCopyPromptInput): string {
  assertNoTemplateLeak(input, 'buildServiceCopyPrompt');
  const { strategy, uiblocks, oneLiner, businessName, offer, goal, understanding } = input;

  const sectionSpecs = strategy.sections
    .map((sectionType) => {
      const layout = uiblocks[sectionType];
      if (!layout) return null;
      return buildSectionSpec(sectionType, layout);
    })
    .filter(Boolean)
    .join('\n\n');

  return `## IDENTITY
You are a conversion copywriter for a service business landing page. The page uses the Hearth design family — warm, editorial, founder-to-founder. You write in that voice, not generic SaaS landing-page voice.

## PROVIDER
One-liner: ${oneLiner}
Business name: ${businessName || '—'}
Service type: ${understanding.serviceType}
What they do: ${understanding.whatYouDo}
Services offered: ${understanding.services.join(', ') || '—'}
Target clients: ${understanding.targetClients.join(', ') || '—'}
Outcomes / differentiators: ${understanding.outcomes.join(', ') || '—'}
Delivery: ${understanding.deliveryModel}
Offer: ${offer}
Landing goal: ${serviceGoalLabels[goal]} (${goal})
${getGoalCtaGuidance(goal)}

## ONE CLIENT (Ideal Reader)
${strategy.oneClient.who}

Awareness: ${strategy.awareness}
${getEmotionalContext(strategy.awareness)}

Core desire: ${strategy.oneClient.coreDesire}
Core pain: ${strategy.oneClient.corePain}

Pain points:
${strategy.oneClient.pains.map((p) => `- ${p}`).join('\n')}

Desires:
${strategy.oneClient.desires.map((d) => `- ${d}`).join('\n')}

Likely objections:
${strategy.oneClient.objections.map((o) => `- ${o}`).join('\n')}

## OUR POSITION (the Provider)
Promise: ${strategy.ourPosition.promise}
Approach: ${strategy.ourPosition.approach}
Credibility: ${strategy.ourPosition.credibility}

## SERVICE PRESENTATION
Format: ${strategy.servicePresentation.format}
Show process: ${strategy.servicePresentation.showProcess}
Show case studies: ${strategy.servicePresentation.showCaseStudies}

${formatServiceVoiceForPrompt()}

## SECTIONS TO GENERATE

${sectionSpecs}

${getElementSchemas()}

## RULES (MUST FOLLOW)
1. **Italic-accent convention — applies to EVERY section, not just hero.** Every "headline" field AND every "lede" field across ALL sections (hero, services, packages, testimonials, cta — every one) must wrap 1-2 emphasized words in <em>...</em>. The renderer styles them as italic Fraunces. Without <em>, the page reads flat — this is the visual signature of Hearth. Do not skip it on services/packages/cta headlines or on any lede.
   - ⚠️ **LEDES ARE THE #1 MISSED FIELD.** A lede is a full descriptive sentence, so it is easy to forget the accent — but it needs exactly one <em>...</em> just like a headline. Pick the single most meaningful word in each lede and wrap it. Re-read every lede before you output.
2. Respect character limits and array min/max strictly.
3. NO placeholder text — every field must be real, usable copy.
4. NO invented exact numbers, client names, or dollar figures. Use ranges or "experienced in X" framing.
5. NEEDS_REVIEW elements (price_display, quote, author_*): write realistic copy but use general framing — founder will verify.
6. For arrays: return the actual array, respecting min/max.
7. Return ONLY valid JSON. No markdown, no commentary.
8. **Output EVERY section listed above — no omissions.** Include each section key (header, hero, services, testimonials, packages, cta, footer — whichever are listed) with a complete "elements" object. Do not drop trailing sections like testimonials or footer.
9. Use Hearth voice — concrete nouns, craftsperson tone. **Avoid the forbidden words ANYWHERE** — including invented brand names (logo_text), company names (author_company), copyright lines, and testimonial quotes. E.g. do NOT name the business "Leverage ..." or "... Solutions" and do NOT let a quote say "game-changing".

## FINAL SELF-CHECK (do this before returning)
Scan your JSON once more and fix any miss:
(a) Every section listed in "SECTIONS TO GENERATE" has an entry.
(b) Every "headline" contains an <em>...</em>.
(c) Every "lede" contains an <em>...</em> — this is the field most often missed.

## OUTPUT FORMAT

Return a JSON object keyed by section type. Each value has an "elements" object:

EXAMPLE (using an unrelated niche — vintage bookbinding studio — to illustrate the SHAPE only. Do NOT copy these words. Write fresh copy for the provider above.)

{
  "hero": {
    "elements": {
      "eyebrow": "BOOKBINDING SINCE 2014",
      "headline": "Library bindings that <em>outlast</em> the books inside them.",
      "lede": "A small studio for collectors and archivists who want every spine to feel as <em>considered</em> as the volume it protects.",
      "cta_text": "Request a quote"
    }
  },
  "services": {
    "elements": {
      "headline": "What we <em>repair</em>",
      "services": [
        { "id": "", "title": "Spine restoration", "description": "...", "icon": "Sparkles", "cta_text": "Learn more" }
      ]
    }
  },
  "packages": {
    "elements": {
      "headline": "Three ways to <em>begin</em>",
      "lede": "Quotes scoped to the condition of your <em>volume</em>, not a generic page count.",
      "packages": [
        { "id": "", "name": "Single Volume", "price_display": "from $200", "timeline": "2 weeks", "features": ["..."], "cta_text": "Request quote", "is_featured": false }
      ]
    }
  },
  "cta": {
    "elements": {
      "headline": "Bring us your <em>oldest</em> book.",
      "lede": "A short call to assess condition and walk through what <em>restoration</em> would look like.",
      "cta_text": "Book an assessment"
    }
  }
}

Every "headline" and every "lede" above shows <em> wrapping. Match this PATTERN — but with words and ideas drawn from THIS provider's offering, not the bookbinding example.

Optional elements may be set to null to exclude them.

Generate copy now:`;
}

/**
 * Retry prompt when the previous attempt failed to parse.
 */
export function buildServiceCopyRetryPrompt(
  originalPrompt: string,
  parseError: string,
  invalidSnippet: string
): string {
  return `${originalPrompt}

---
PREVIOUS ATTEMPT FAILED TO PARSE

Error: ${parseError}
Invalid snippet: ${invalidSnippet.slice(0, 500)}

Common issues: trailing commas, unescaped quotes in strings, missing closing braces, comments in JSON.

Return the complete, valid JSON response (no markdown wrapping, no commentary):`;
}
