/**
 * Generation types for elements:
 * - ai_generated: AI generates content, ready to use
 * - manual_preferred: User provides (logo, hero_image), has defaults
 * - ai_generated_needs_review: AI generates placeholder, flagged "Verify this"
 * - system: Auto-generated by code (IDs, timestamps)
 * - hybrid: Mix of AI and manual (legacy, avoid using)
 */
export type GenerationType = 'ai_generated' | 'manual_preferred' | 'ai_generated_needs_review' | 'system' | 'hybrid';

export type RequirementType = 'required' | 'optional';

// =============================================================================
// NEW SCHEMA FORMAT (V2) - Clean arrays, no pipe strings
// =============================================================================

/** Element definition in new schema format */
export interface ElementDef {
  type: 'string' | 'boolean' | 'number';
  requirement?: RequirementType;  // Only applies to ai_generated
  fillMode: GenerationType;
  default?: any;  // Placeholder for manual_preferred
  toggleGroup?: string;  // Elements with same group are hidden from toggle modal, controlled by group's parent
}

/** Collection field definition */
export interface CollectionFieldDef {
  type: 'string' | 'boolean' | 'number' | 'string[]' | 'array';
  fillMode: GenerationType;
  default?: any;
  constraints?: { min: number; max: number };
  fields?: Record<string, CollectionFieldDef>;  // For nested arrays
}

/** Collection (array of items) definition */
export interface CollectionDef {
  requirement: RequirementType;
  fillMode: GenerationType;
  constraints: { min: number; max: number };
  fields: Record<string, CollectionFieldDef>;
  toggleGroup?: string;  // Controlled by group's parent toggle
}

/** New UIBlock schema format (V2) */
export interface UIBlockSchemaV2 {
  sectionType: string;
  elements: Record<string, ElementDef>;
  collections?: Record<string, CollectionDef>;
}

// =============================================================================
// LEGACY SCHEMA FORMAT (V1) - For backward compatibility during migration
// =============================================================================

export interface LayoutElement {
  element: string;
  mandatory: boolean;
  generation?: GenerationType;
  isCard?: boolean; // Indicates if this element is part of a card structure
  description?: string; // Optional description or guidance for the element
  charLimit?: number; // Maximum character length for this element
}

export interface CardStructure {
  type: 'cards' | 'pairs' | 'items' | 'blocks' | 'steps' | 'triplets' | 'quadruplets' | 'sextuplets' | 'tabbed_pairs' | 'rows' | 'usage_based' | 'column_pairs';
  elements: string[];  // All card elements are mandatory by default
  generation: GenerationType;
}

export interface CardRequirements {
  type: string;
  min: number;
  max: number;
  optimal: [number, number];
  description: string;
  respectUserContent?: boolean; // Prioritize user-provided features
}

export interface UnifiedLayoutElement {
  sectionElements: LayoutElement[];
  cardStructure?: CardStructure;
  cardRequirements: CardRequirements | null;
}

// =============================================================================
// COMBINED SCHEMA TYPE - Supports both V1 and V2 formats
// =============================================================================

export interface LayoutSchema {
  [layoutName: string]: LayoutElement[] | UnifiedLayoutElement | UIBlockSchemaV2;
}

// =============================================================================
// HELPER FUNCTIONS - Support V1 (legacy) and V2 (new) schema formats
// =============================================================================

type AnySchema = LayoutElement[] | UnifiedLayoutElement | UIBlockSchemaV2;

/** Check if schema is V2 format */
export function isV2Schema(schema: AnySchema): schema is UIBlockSchemaV2 {
  return typeof schema === 'object' && !Array.isArray(schema) && 'sectionType' in schema && 'elements' in schema;
}

/** Check if schema is V1 unified format */
export function isUnifiedSchema(schema: AnySchema): schema is UnifiedLayoutElement {
  return typeof schema === 'object' && !Array.isArray(schema) && 'sectionElements' in schema;
}

/** Convert V2 elements to V1 LayoutElement[] for backward compatibility */
function v2ElementsToV1(schema: UIBlockSchemaV2): LayoutElement[] {
  const elements: LayoutElement[] = [];

  // Convert section elements
  for (const [key, def] of Object.entries(schema.elements)) {
    elements.push({
      element: key,
      mandatory: def.requirement === 'required',
      generation: def.fillMode
    });
  }

  // Convert collection fields (excluding 'id' which is system-generated)
  if (schema.collections) {
    for (const [collectionName, collection] of Object.entries(schema.collections)) {
      for (const [fieldKey, fieldDef] of Object.entries(collection.fields)) {
        if (fieldDef.fillMode !== 'system') {
          elements.push({
            element: `${collectionName}.${fieldKey}`,
            mandatory: collection.requirement === 'required',
            generation: fieldDef.fillMode,
            isCard: true
          });
        }
      }
    }
  }

  return elements;
}

/** Get all elements from any schema format (returns V1 format for compatibility) */
export function getAllElements(schema: AnySchema): LayoutElement[] {
  if (isV2Schema(schema)) {
    return v2ElementsToV1(schema);
  }
  if (isUnifiedSchema(schema)) {
    const cardElements = schema.cardStructure ? schema.cardStructure.elements.map(elementName => ({
      element: elementName,
      mandatory: true,
      generation: schema.cardStructure!.generation
    })) : [];
    return [...schema.sectionElements, ...cardElements];
  }
  return schema;
}

/** Get layout elements safely for any schema format */
export function getLayoutElements(layoutName: string): LayoutElement[] {
  const schema = layoutElementSchema[layoutName];
  if (!schema) {
    return [];
  }
  return getAllElements(schema);
}

/** Get section elements (non-card elements) */
export function getSectionElements(schema: AnySchema): LayoutElement[] {
  if (isV2Schema(schema)) {
    return Object.entries(schema.elements).map(([key, def]) => ({
      element: key,
      mandatory: def.requirement === 'required',
      generation: def.fillMode
    }));
  }
  if (isUnifiedSchema(schema)) {
    return schema.sectionElements;
  }
  return schema;
}

/** Get card/collection elements */
export function getCardElements(schema: AnySchema): LayoutElement[] {
  if (isV2Schema(schema) && schema.collections) {
    const elements: LayoutElement[] = [];
    for (const [collectionName, collection] of Object.entries(schema.collections)) {
      for (const [fieldKey, fieldDef] of Object.entries(collection.fields)) {
        if (fieldDef.fillMode !== 'system') {
          elements.push({
            element: `${collectionName}.${fieldKey}`,
            mandatory: collection.requirement === 'required',
            generation: fieldDef.fillMode,
            isCard: true
          });
        }
      }
    }
    return elements;
  }
  if (isUnifiedSchema(schema) && schema.cardStructure) {
    return schema.cardStructure.elements.map(elementName => ({
      element: elementName,
      mandatory: true,
      generation: schema.cardStructure!.generation
    }));
  }
  return [];
}

/** Get card requirements from any schema format */
export function getCardRequirements(schema: AnySchema): CardRequirements | null {
  if (isV2Schema(schema) && schema.collections) {
    // Return requirements for first collection (most UIBlocks have one)
    const firstCollection = Object.entries(schema.collections)[0];
    if (firstCollection) {
      const [name, def] = firstCollection;
      return {
        type: name,
        min: def.constraints.min,
        max: def.constraints.max,
        optimal: [def.constraints.min, def.constraints.max],
        description: `${name} items`
      };
    }
  }
  if (isUnifiedSchema(schema)) {
    return schema.cardRequirements || null;
  }
  return null;
}

/**
 * Apply schema defaults for V2 schemas.
 * Injects manual_preferred defaults for elements not present in AI output.
 */
export function applySchemaDefaults(
  uiblockName: string,
  aiElements: Record<string, any>
): Record<string, any> {
  const schema = layoutElementSchema[uiblockName];
  if (!schema || !isV2Schema(schema)) {
    // Still filter nulls for non-V2 schemas
    return Object.fromEntries(
      Object.entries(aiElements).filter(([_, v]) => v !== null)
    );
  }

  // Filter out null values from AI response (Claude returns explicit nulls for optional elements)
  const result = Object.fromEntries(
    Object.entries(aiElements).filter(([_, v]) => v !== null)
  );

  // Apply element defaults - ONLY for required manual_preferred
  for (const [key, def] of Object.entries(schema.elements)) {
    if (def.fillMode === 'manual_preferred' &&
        def.requirement === 'required' &&
        def.default !== undefined) {
      if (result[key] === undefined || result[key] === null) {
        result[key] = def.default;
      }
    }
  }

  // Apply collection defaults - ONLY for required manual_preferred
  if (schema.collections) {
    for (const [name, collection] of Object.entries(schema.collections)) {
      if (collection.fillMode === 'manual_preferred' &&
          collection.requirement === 'required') {
        if (result[name] === undefined || result[name] === null) {
          result[name] = [];
        }
      }
    }
  }

  return result;
}

/**
 * Apply schema defaults to all sections in copy response.
 */
export function applyAllSchemaDefaults(
  sections: Record<string, { elements: Record<string, any> }>,
  uiblocks: Record<string, string>
): Record<string, { elements: Record<string, any> }> {
  const result: Record<string, { elements: Record<string, any> }> = {};

  for (const [sectionName, sectionCopy] of Object.entries(sections)) {
    const uiblockName = uiblocks[sectionName];
    result[sectionName] = {
      elements: uiblockName
        ? applySchemaDefaults(uiblockName, sectionCopy.elements || {})
        : (sectionCopy.elements || {})
    };
  }

  return result;
}

/**
 * Get schema defaults in the shape useLayoutComponent expects.
 * Converts V2 central schema → { key: { type, default } } map.
 * Used as fallback when UIBlock doesn't pass contentSchema prop.
 */
export function getSchemaDefaults(layoutName: string): Record<string, { type: 'string' | 'array' | 'boolean' | 'number'; default: any }> | null {
  const schema = layoutElementSchema[layoutName];
  if (!schema || !isV2Schema(schema)) return null;

  type SchemaEntry = { type: 'string' | 'array' | 'boolean' | 'number'; default: any };
  const defaults: Record<string, SchemaEntry> = {};

  for (const [key, def] of Object.entries(schema.elements)) {
    defaults[key] = { type: def.type as SchemaEntry['type'], default: def.default ?? '' };
  }

  // Collections get type 'array' with default []
  if (schema.collections) {
    for (const collectionName of Object.keys(schema.collections)) {
      defaults[collectionName] = { type: 'array', default: [] };
    }
  }

  return defaults;
}

export const layoutElementSchema: LayoutSchema = {
  // BeforeAfter Section - V2 Schema
  SideBySideBlocks: {
    sectionType: "SideBySideBlocks",

    elements: {
      headline:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Your Transformation Story" },
      before_label:       { type: "string", requirement: "required", fillMode: "ai_generated", default: "Before" },
      after_label:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "After" },
      before_description: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      after_description:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      subheadline:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      summary_text:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      before_icon:        { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "XCircle" },
      after_icon:         { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "CheckCircle" },
    },

    collections: {
      before_points: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated", default: "" },
        }
      },
      after_points: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated", default: "" },
        }
      },
    }
  },

  // BeforeAfter Section - V2 Schema
  StackedTextVisual: {
    sectionType: "StackedTextVisual",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Transform Your Experience" },
      before_text:     { type: "string", requirement: "required", fillMode: "ai_generated", default: "Struggling with manual processes, disconnected tools, and delayed insights that slow down your progress." },
      after_text:      { type: "string", requirement: "required", fillMode: "ai_generated", default: "Enjoy automated workflows, unified data, and instant insights that accelerate your success." },
      before_label:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Before" },
      after_label:     { type: "string", requirement: "required", fillMode: "ai_generated", default: "After" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      transition_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      summary_text:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      before_icon:     { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "Plus" },
      after_icon:      { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "Zap" },
      transition_icon: { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "ArrowDown" },
    },
    // No collections - no trust_items/cta per user decision
  },

  // BeforeAfter Section - V2 Schema
  SplitCard: {
    sectionType: "SplitCard",

    elements: {
      headline:             { type: "string", requirement: "required", fillMode: "ai_generated", default: "Premium Transformation Experience" },
      before_label:         { type: "string", requirement: "required", fillMode: "ai_generated", default: "Current Challenge" },
      after_label:          { type: "string", requirement: "required", fillMode: "ai_generated", default: "Premium Solution" },
      before_description:   { type: "string", requirement: "required", fillMode: "ai_generated", default: "Complex manual processes requiring expertise, time, and significant resources to execute properly." },
      after_description:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Expertly crafted automation that delivers exceptional results with minimal effort and maximum efficiency." },
      subheadline:          { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      summary_text:         { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      upgrade_text:         { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Upgrade" },
      before_visual:        { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "/Before default.jpg" },
      after_visual:         { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "/After default.jpg" },
      before_icon:          { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "AlertTriangle" },
      after_icon:           { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "Star" },
      upgrade_icon:         { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "ArrowRight" },
    },
    // No collections - no trust_items/cta per user decision
  },

  // FAQ Section - AccordionFAQ (V2 Schema)
  AccordionFAQ: {
    sectionType: "AccordionFAQ",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Frequently Asked Questions" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Find answers to common questions about our platform and services." },
      contact_prompt:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      cta_text:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      faq_items: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 10 },
        fields: {
          id:       { type: "string", fillMode: "system" },
          question: { type: "string", fillMode: "ai_generated", default: "" },
          answer:   { type: "string", fillMode: "ai_generated", default: "" },
        }
      }
    }
  },

  // FAQ Section - TwoColumnFAQ (V2 Schema)
  TwoColumnFAQ: {
    sectionType: "TwoColumnFAQ",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Frequently Asked Questions" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Everything you need to know about our platform" },
      contact_prompt:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      cta_text:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      faq_items: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 4, max: 10 },
        fields: {
          id:       { type: "string", fillMode: "system" },
          question: { type: "string", fillMode: "ai_generated", default: "" },
          answer:   { type: "string", fillMode: "ai_generated", default: "" },
        }
      }
    }
  },

  // FAQ Section - InlineQnAList (V2 Schema)
  InlineQnAList: {
    sectionType: "InlineQnAList",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Quick Questions & Answers" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Get instant answers to the most common questions" },
      contact_prompt:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      cta_text:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      faq_items: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 8 },
        fields: {
          id:       { type: "string", fillMode: "system" },
          question: { type: "string", fillMode: "ai_generated", default: "" },
          answer:   { type: "string", fillMode: "ai_generated", default: "" },
        }
      }
    }
  },

  // FAQ Section - SegmentedFAQTabs (V2 Schema)
  SegmentedFAQTabs: {
    sectionType: "SegmentedFAQTabs",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Everything You Need to Know" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Find answers organized by topic for easy navigation" },
      contact_prompt:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      cta_text:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      tabs: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 4 },
        fields: {
          id:    { type: "string", fillMode: "system" },
          label: { type: "string", fillMode: "ai_generated", default: "" },
          items: {
            type: "array",
            fillMode: "ai_generated",
            constraints: { min: 2, max: 5 },
            fields: {
              id:       { type: "string", fillMode: "system" },
              question: { type: "string", fillMode: "ai_generated", default: "" },
              answer:   { type: "string", fillMode: "ai_generated", default: "" },
            }
          }
        }
      }
    }
  },

  // Features Section - V2 Schema
  IconGrid: {
    sectionType: "IconGrid",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Core Features" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      badge_text:      { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      features: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 9 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // SplitAlternating - V2 Schema
  SplitAlternating: {
    sectionType: "SplitAlternating",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Advanced Features" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      features: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          visual:      { type: "string", fillMode: "manual_preferred" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // MetricTiles - V2 Schema (focused on metrics, no CTA/trust)
  MetricTiles: {
    sectionType: "MetricTiles",

    elements: {
      headline:          { type: "string", requirement: "required", fillMode: "ai_generated", default: "Quantifiable Results" },
      subheadline:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      show_roi_summary:  { type: "boolean", fillMode: "manual_preferred", default: true },
      roi_summary_title: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      roi_description:   { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      metrics: {
        requirement: "required",
        fillMode: "ai_generated_needs_review",
        constraints: { min: 2, max: 8 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated" },
          metric:      { type: "string", fillMode: "ai_generated_needs_review" },
          label:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
        }
      },
      roi_metrics: {
        requirement: "optional",
        fillMode: "ai_generated_needs_review",
        constraints: { min: 0, max: 3 },
        fields: {
          id:     { type: "string", fillMode: "system" },
          metric: { type: "string", fillMode: "ai_generated_needs_review" },
          label:  { type: "string", fillMode: "ai_generated" },
        }
      }
    }
  },

  // Features Section - V2 Schema
  Carousel: {
    sectionType: "Carousel",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Feature Showcase" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      auto_play:       { type: "boolean", fillMode: "manual_preferred", default: false },
      // Benefits shown per slide (section-level, same on all slides)
      benefit_1:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      benefit_2:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      benefit_icon_1:  { type: "string", fillMode: "manual_preferred", default: "Check" },
      benefit_icon_2:  { type: "string", fillMode: "manual_preferred", default: "Clock" },
    },

    collections: {
      features: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          visual:      { type: "string", fillMode: "manual_preferred" },
          tag:         { type: "string", fillMode: "ai_generated" },
        }
      }
    }
  },

  // FounderNote Section - V2 Schema
  LetterStyleBlock: {
    sectionType: "LetterStyleBlock",

    elements: {
      // Required AI-generated
      letter_header:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "A Personal Note from Our Founder" },
      letter_greeting:  { type: "string", requirement: "required", fillMode: "ai_generated", default: "Dear Fellow Builder," },
      letter_body:      { type: "string", requirement: "required", fillMode: "ai_generated", default: "Three years ago, I sat exactly where you are now—staring at a landing page that just wouldn't convert.\n\nI'd tried everything. Hired expensive copywriters. A/B tested until my eyes crossed. Read every marketing book I could find.\n\nThen it hit me: the problem wasn't my copy. It was the process. Great landing pages need great strategy first.\n\nThat's why I built Lessgo. To give founders like us the strategic foundation we need before writing a single word." },
      letter_signature: { type: "string", requirement: "required", fillMode: "ai_generated", default: "Sushant Jain" },

      // Optional AI-generated
      founder_title:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Founder" },
      company_name:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Lessgo" },
      date_text:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "January 2025" },
      ps_text:          { type: "string", requirement: "optional", fillMode: "ai_generated", default: "P.S. Every founder who joins gets a personal strategy review from me. Just reply to your welcome email." },

      // Manual preferred
      founder_image:    { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "/images/founder.jpg" },
    },

    collections: {}
  },

  // Hero Section - V2 Schema
  leftCopyRightImage: {
    sectionType: "leftCopyRightImage",

    elements: {
      // Required AI-generated
      headline:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Transform Your Business with Smart Automation" },
      subheadline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Streamline workflows, boost productivity, and scale effortlessly with our intelligent automation platform." },
      cta_text:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Start Free Trial" },

      // Optional AI-generated
      secondary_cta_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Save 20+ hours per week with automated workflows that just work." },
      badge_text:         { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },

      // Manual preferred - required (show with placeholder)
      hero_image:         { type: "string", requirement: "required", fillMode: "manual_preferred", default: "/hero-placeholder.jpg" },

      // Manual preferred - optional (user adds via toolbar)
      show_social_proof:  { type: "boolean", requirement: "optional", fillMode: "manual_preferred", default: true },
      show_customer_avatars: { type: "boolean", requirement: "optional", fillMode: "manual_preferred", default: true, toggleGroup: "show_social_proof" },

      // Social proof children (controlled by show_social_proof toggle)
      customer_count:     { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "500+ happy customers", toggleGroup: "show_social_proof" },
      rating_value:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "4.9/5", toggleGroup: "show_social_proof" },
      rating_count:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "from 127 reviews", toggleGroup: "show_social_proof" },
    },

    collections: {
      trust_items: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated" },
        }
      },
      customer_avatars: {
        requirement: "optional",
        fillMode: "manual_preferred",
        toggleGroup: "show_social_proof",
        constraints: { min: 0, max: 6 },
        fields: {
          id:         { type: "string", fillMode: "system" },
          name:       { type: "string", fillMode: "manual_preferred", default: "Customer" },
          avatar_url: { type: "string", fillMode: "manual_preferred", default: "" },
        }
      }
    }
  },

  // Hero Section - V2 Schema
  centerStacked: {
    sectionType: "centerStacked",

    elements: {
      // Required AI-generated
      headline:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Transform Your Business with Smart Automation" },
      subheadline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Streamline workflows, boost productivity, and scale effortlessly with our intelligent automation platform." },
      cta_text:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Start Free Trial" },

      // Optional AI-generated
      secondary_cta_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Save 20+ hours per week with automated workflows that just work." },
      badge_text:         { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },

      // Manual preferred - required (show with placeholder)
      center_hero_image:  { type: "string", requirement: "required", fillMode: "manual_preferred", default: "/hero-placeholder.jpg" },

      // Manual preferred - optional (user adds via toolbar)
      show_social_proof:  { type: "boolean", requirement: "optional", fillMode: "manual_preferred", default: true },
      show_customer_avatars: { type: "boolean", requirement: "optional", fillMode: "manual_preferred", default: true, toggleGroup: "show_social_proof" },

      // Social proof children (controlled by show_social_proof toggle)
      customer_count:     { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "500+ happy customers", toggleGroup: "show_social_proof" },
      rating_value:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "4.9/5", toggleGroup: "show_social_proof" },
      rating_count:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "from 127 reviews", toggleGroup: "show_social_proof" },
    },

    collections: {
      trust_items: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated" },
        }
      },
      customer_avatars: {
        requirement: "optional",
        fillMode: "manual_preferred",
        toggleGroup: "show_social_proof",
        constraints: { min: 0, max: 6 },
        fields: {
          id:         { type: "string", fillMode: "system" },
          name:       { type: "string", fillMode: "manual_preferred", default: "Customer" },
          avatar_url: { type: "string", fillMode: "manual_preferred", default: "" },
        }
      }
    }
  },

  // Hero Section - V2 Schema
  splitScreen: {
    sectionType: "splitScreen",

    elements: {
      // Required AI-generated
      headline:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Transform Your Business with Smart Automation" },
      subheadline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Streamline workflows, boost productivity, and scale effortlessly with our intelligent automation platform." },
      cta_text:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Start Free Trial" },

      // Optional AI-generated
      secondary_cta_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Save 20+ hours per week with automated workflows that just work." },
      badge_text:         { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      value_proposition:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },

      // Manual preferred - required (show with placeholder)
      split_hero_image:   { type: "string", requirement: "required", fillMode: "manual_preferred", default: "/hero-placeholder.jpg" },

      // Manual preferred - optional (user adds via toolbar)
      show_social_proof:  { type: "boolean", requirement: "optional", fillMode: "manual_preferred", default: true },
      show_customer_avatars: { type: "boolean", requirement: "optional", fillMode: "manual_preferred", default: true, toggleGroup: "show_social_proof" },

      // Social proof children (controlled by show_social_proof toggle)
      customer_count:     { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "500+ happy customers", toggleGroup: "show_social_proof" },
      rating_value:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "4.9/5", toggleGroup: "show_social_proof" },
      rating_count:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "from 127 reviews", toggleGroup: "show_social_proof" },
    },

    collections: {
      trust_items: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated" },
        }
      },
      customer_avatars: {
        requirement: "optional",
        fillMode: "manual_preferred",
        toggleGroup: "show_social_proof",
        constraints: { min: 0, max: 6 },
        fields: {
          id:         { type: "string", fillMode: "system" },
          name:       { type: "string", fillMode: "manual_preferred", default: "Customer" },
          avatar_url: { type: "string", fillMode: "manual_preferred", default: "" },
        }
      }
    }
  },

  imageFirst: {
    sectionType: "imageFirst",

    elements: {
      // Required AI-generated
      headline:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Transform Your Business with Smart Automation" },
      subheadline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Streamline workflows, boost productivity, and scale effortlessly with our intelligent automation platform." },
      cta_text:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Start Free Trial" },

      // Optional AI-generated
      secondary_cta_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Save 20+ hours per week with automated workflows that just work." },
      badge_text:         { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },

      // Manual preferred - required
      image_first_hero_image: { type: "string", requirement: "required", fillMode: "manual_preferred", default: "/hero-placeholder.jpg" },

      // Manual preferred - optional
      show_social_proof:     { type: "boolean", requirement: "optional", fillMode: "manual_preferred", default: true },
      show_customer_avatars: { type: "boolean", requirement: "optional", fillMode: "manual_preferred", default: true, toggleGroup: "show_social_proof" },

      // Social proof children (controlled by show_social_proof toggle)
      customer_count:     { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "500+ happy customers", toggleGroup: "show_social_proof" },
      rating_value:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "4.9/5", toggleGroup: "show_social_proof" },
      rating_count:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "from 127 reviews", toggleGroup: "show_social_proof" },
    },

    collections: {
      trust_items: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated" },
        }
      },
      customer_avatars: {
        requirement: "optional",
        fillMode: "manual_preferred",
        toggleGroup: "show_social_proof",
        constraints: { min: 0, max: 6 },
        fields: {
          id:         { type: "string", fillMode: "system" },
          name:       { type: "string", fillMode: "manual_preferred", default: "Customer" },
          avatar_url: { type: "string", fillMode: "manual_preferred", default: "" },
        }
      }
    }
  },

  // HowItWorks Section - V2 Schema
  ThreeStepHorizontal: {
    sectionType: "ThreeStepHorizontal",

    elements: {
      // Required AI-generated
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "How It Works" },

      // Optional AI-generated
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      conclusion_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      steps: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // HowItWorks Section - VerticalTimeline (V2 Schema)
  VerticalTimeline: {
    sectionType: "VerticalTimeline",

    elements: {
      headline:             { type: "string", requirement: "required", fillMode: "ai_generated", default: "Our Process" },
      subheadline:          { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      process_summary_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      steps: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          duration:    { type: "string", fillMode: "ai_generated" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  AccordionSteps: {
    sectionType: "AccordionSteps",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Implementation Guide" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      conclusion_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      steps: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          details:     { type: "string", fillMode: "ai_generated" },
        }
      }
    }
  },

  // HowItWorks Section - VideoWalkthrough (V2 Schema)
  VideoWalkthrough: {
    sectionType: "VideoWalkthrough",

    elements: {
      // Required AI-generated
      headline:          { type: "string", requirement: "required", fillMode: "ai_generated", default: "See How It Works" },
      video_title:       { type: "string", requirement: "required", fillMode: "ai_generated", default: "Product Demo" },
      video_description: { type: "string", requirement: "required", fillMode: "ai_generated", default: "Watch a quick walkthrough of our platform." },

      // Optional AI-generated
      subheadline:         { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      demo_stats_heading:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },

      // Manual preferred
      video_url:       { type: "string", fillMode: "manual_preferred", default: "" },
      video_duration:  { type: "string", fillMode: "manual_preferred", default: "" },
    },

    collections: {
      demo_stats: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 3 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          label:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      },
      video_info: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 2 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated" },
          icon: { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // Objection Section - MythVsRealityGrid (V2 Schema)
  // Uses fixed Lucide icons: X for Myth, Check for Reality
  MythVsRealityGrid: {
    sectionType: "MythVsRealityGrid",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Separating Myth from Reality" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Let's address the common misconceptions and show you what's actually true." },
    },

    collections: {
      pairs: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:      { type: "string", fillMode: "system" },
          myth:    { type: "string", fillMode: "ai_generated", default: "" },
          reality: { type: "string", fillMode: "ai_generated", default: "" },
        }
      }
    }
  },

  // Objection Section - VisualObjectionTiles (V2 Schema)
  VisualObjectionTiles: {
    sectionType: "VisualObjectionTiles",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Common Concerns? We've Got You Covered" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Here are the questions we hear most often and why they shouldn't hold you back." },
    },

    collections: {
      objections: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:       { type: "string", fillMode: "system" },
          question: { type: "string", fillMode: "ai_generated", default: "" },
          response: { type: "string", fillMode: "ai_generated", default: "" },
          label:    { type: "string", fillMode: "ai_generated", default: "" },
          icon:     { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // Pricing Section - TierCards (V2 Schema)
  TierCards: {
    sectionType: "TierCards",

    elements: {
      headline:          { type: "string", requirement: "required", fillMode: "ai_generated", default: "Simple, Transparent Pricing" },
      subheadline:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      badge_text:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      billing_note:      { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      guarantee_text:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      highlighted_label: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Most Popular" },
    },

    collections: {
      tiers: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 4 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          name:        { type: "string", fillMode: "ai_generated" },
          price:       { type: "string", fillMode: "ai_generated_needs_review" },
          period:      { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          features:    { type: "string[]", fillMode: "ai_generated", constraints: { min: 3, max: 8 } },
          cta_text:    { type: "string", fillMode: "ai_generated" },
          highlighted: { type: "boolean", fillMode: "manual_preferred", default: false },
        }
      }
    }
  },

  // Pricing Section - ToggleableMonthlyYearly (V2 Schema)
  ToggleableMonthlyYearly: {
    sectionType: "ToggleableMonthlyYearly",

    elements: {
      headline:              { type: "string", requirement: "required", fillMode: "ai_generated", default: "Choose Your Plan" },
      subheadline:           { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      annual_discount_label: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      billing_note:          { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      tiers: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 4 },
        fields: {
          id:             { type: "string", fillMode: "system" },
          name:           { type: "string", fillMode: "ai_generated" },
          monthly_price:  { type: "string", fillMode: "ai_generated_needs_review" },
          yearly_price:   { type: "string", fillMode: "ai_generated_needs_review" },
          description:    { type: "string", fillMode: "ai_generated" },
          features:       { type: "string[]", fillMode: "ai_generated", constraints: { min: 3, max: 8 } },
          cta_text:       { type: "string", fillMode: "ai_generated" },
          is_popular:     { type: "boolean", fillMode: "manual_preferred", default: false },
        }
      }
    }
  },

  // V3 ARCHIVED: SliderPricing - moved to archive/schemas/layoutElementSchema.archived.ts

  CallToQuotePlan: {
    sectionType: "CallToQuotePlan",

    elements: {
      headline:          { type: "string", requirement: "required", fillMode: "ai_generated", default: "Let's Talk About Your Needs" },
      value_proposition: { type: "string", requirement: "required", fillMode: "ai_generated", default: "Custom solutions tailored to your business" },
      subheadline:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      supporting_text:   { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      response_time:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      contact_cards: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 4 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          cta:         { type: "string", fillMode: "ai_generated" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      },
      trust_items: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated" },
        }
      }
    }
  },

  // Problem Section - V2 Schema
  StackedPainBullets: {
    sectionType: "StackedPainBullets",

    elements: {
      headline:        { type: "string", requirement: "required", fillMode: "ai_generated", default: "Are You Struggling With These Daily Frustrations?" },
      subheadline:     { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      conclusion_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Sound familiar? You're not alone." },
    },

    collections: {
      pain_items: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          point:       { type: "string", fillMode: "ai_generated", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // Results Section
  StatBlocks: {
    sectionType: "StatBlocks",

    elements: {
      headline:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Our Results Speak for Themselves" },
      subheadline:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      achievement_footer: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      stats: {
        requirement: "required",
        fillMode: "ai_generated_needs_review",
        constraints: { min: 2, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          value:       { type: "string", fillMode: "ai_generated_needs_review" },
          label:       { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // Results Section - StackedWinsList (V2 Schema)
  StackedWinsList: {
    sectionType: "StackedWinsList",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Real Results, Real Impact" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      footer_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      // Icon: no default - derive at render time per Icon Handling Pattern
      win_icon:    { type: "string", fillMode: "manual_preferred" },
    },

    collections: {
      wins: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 8 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          win:         { type: "string", fillMode: "ai_generated" },
          description: { type: "string", fillMode: "ai_generated" },
          category:    { type: "string", fillMode: "ai_generated" },
        }
      }
    }
  },

  // Results Section - ResultsGallery (V2 Schema)
  ResultsGallery: {
    sectionType: "ResultsGallery",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Success Stories" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      gallery_items: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 4 },
        fields: {
          id:        { type: "string", fillMode: "system" },
          image_url: { type: "string", fillMode: "manual_preferred", default: "" },
          caption:   { type: "string", fillMode: "ai_generated" },
        }
      }
    }
  },

  // SocialProof Section - V2 Schema
  // SocialProof Section - V2 Schema (Tiered Hierarchy)
  // PRIMARY: Company logos | SECONDARY: Press pills | TERTIARY: Certs + Stats inline
  LogoWall: {
    sectionType: "LogoWall",

    elements: {
      // Required AI-generated
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Trusted by Leading Companies Worldwide" },

      // Optional AI-generated
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Join thousands of companies that trust us to power their success." },

      // Tier toggles
      show_press:  { type: "boolean", fillMode: "manual_preferred", default: true },  // Secondary tier
      show_badges: { type: "boolean", fillMode: "manual_preferred", default: true },  // Tertiary tier (certs + stats)
    },

    collections: {
      companies: {
        requirement: "required",
        fillMode: "manual_preferred",
        constraints: { min: 4, max: 12 },
        fields: {
          id:       { type: "string", fillMode: "system" },
          name:     { type: "string", fillMode: "manual_preferred", default: "Company Name" },
          logo_url: { type: "string", fillMode: "manual_preferred", default: "" },
        }
      },

      stats: {
        requirement: "optional",
        fillMode: "ai_generated_needs_review",
        constraints: { min: 0, max: 3 },
        fields: {
          id:    { type: "string", fillMode: "system" },
          value: { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          label: { type: "string", fillMode: "ai_generated", default: "" },
        }
      },

      media_mentions: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:    { type: "string", fillMode: "system" },
          name:  { type: "string", fillMode: "ai_generated", default: "" },
          quote: { type: "string", fillMode: "ai_generated", default: "" },
        }
      },

      certifications: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:    { type: "string", fillMode: "system" },
          code:  { type: "string", fillMode: "ai_generated", default: "" },
          label: { type: "string", fillMode: "ai_generated", default: "" },
        }
      },
    }
  },

  // Testimonial Section - V2 Schema
  QuoteGrid: {
    sectionType: "QuoteGrid",

    elements: {
      headline:             { type: "string", requirement: "required", fillMode: "ai_generated", default: "What Our Customers Are Saying" },
      subheadline:          { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      verification_message: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "All testimonials from verified customers" },
    },

    collections: {
      testimonials: {
        requirement: "required",
        fillMode: "ai_generated_needs_review",
        constraints: { min: 2, max: 6 },
        fields: {
          id:               { type: "string", fillMode: "system" },
          quote:            { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_name:    { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_title:   { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_company: { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          rating_value:     { type: "string", fillMode: "ai_generated_needs_review", default: "5" },
        }
      }
    }
  },

  // Testimonials Section - VideoTestimonials (V2 Schema)
  VideoTestimonials: {
    sectionType: "VideoTestimonials",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "See What Our Customers Are Saying" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      video_testimonials: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 1, max: 6 },
        fields: {
          id:               { type: "string", fillMode: "system" },
          title:            { type: "string", fillMode: "ai_generated", default: "" },
          description:      { type: "string", fillMode: "ai_generated", default: "" },
          customer_name:    { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_title:   { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_company: { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          video_url:        { type: "string", fillMode: "manual_preferred", default: "" },
          thumbnail:        { type: "string", fillMode: "manual_preferred", default: "" },
        }
      }
    }
  },

  // V3 ARCHIVED: AvatarCarousel schema moved to archive/schemas/layoutElementSchema.archived.ts

  // Testimonials Section - BeforeAfterQuote (V2 Schema)
  BeforeAfterQuote: {
    sectionType: "BeforeAfterQuote",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Real Customer Transformations" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "See how our solution transformed their operations" },
      before_icon: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "XCircle" },
      after_icon:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "CheckCircle" },
    },

    collections: {
      transformations: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 1, max: 4 },
        fields: {
          id:                { type: "string", fillMode: "system" },
          before_situation:  { type: "string", fillMode: "ai_generated", default: "" },
          after_outcome:     { type: "string", fillMode: "ai_generated", default: "" },
          testimonial_quote: { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_name:     { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_title:    { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_company:  { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          before_icon:       { type: "string", fillMode: "ai_generated", default: "Frown" },
          after_icon:        { type: "string", fillMode: "ai_generated", default: "Smile" },
          avatar_url:        { type: "string", fillMode: "manual_preferred", default: "" },
        }
      }
    }
  },

  // Testimonials Section - PullQuoteStack (V2 Schema)
  // B2C equivalent of QuoteGrid - masonry layout with color gradients
  PullQuoteStack: {
    sectionType: "PullQuoteStack",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Real People, Real Results" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      testimonials: {
        requirement: "required",
        fillMode: "ai_generated_needs_review",
        constraints: { min: 2, max: 6 },
        fields: {
          id:               { type: "string", fillMode: "system" },
          quote:            { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_name:    { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_title:   { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          customer_location: { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          avatar_url:       { type: "string", fillMode: "manual_preferred", default: "" },
        }
      }
    }
  },

  // UniqueMechanism Section - V2 Schema
  MethodologyBreakdown: {
    sectionType: "MethodologyBreakdown",

    elements: {
      headline:               { type: "string", requirement: "required", fillMode: "ai_generated", default: "The Science Behind Our Success" },
      methodology_name:       { type: "string", requirement: "required", fillMode: "ai_generated", default: "Adaptive Intelligence Framework™" },
      methodology_description: { type: "string", requirement: "required", fillMode: "ai_generated", default: "Our proprietary methodology combines machine learning, behavioral psychology, and real-time optimization to deliver unprecedented results." },
      subheadline:            { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      results_title:          { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Proven Results" },
      methodology_icon:       { type: "string", fillMode: "manual_preferred", default: "Brain" },
    },

    collections: {
      principles: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          name:        { type: "string", fillMode: "ai_generated", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      },
      results: {
        requirement: "optional",
        fillMode: "ai_generated_needs_review",
        constraints: { min: 0, max: 4 },
        fields: {
          id:     { type: "string", fillMode: "system" },
          metric: { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          label:  { type: "string", fillMode: "ai_generated", default: "" },
        }
      }
    }
  },

  // UniqueMechanism Section - ProcessFlowDiagram (V2 Schema)
  ProcessFlowDiagram: {
    sectionType: "ProcessFlowDiagram",

    elements: {
      headline:       { type: "string", requirement: "required", fillMode: "ai_generated", default: "How Our Unique Process Works" },
      subheadline:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Our proprietary methodology delivers results in simple steps." },
      benefits_title: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Why This Process Works" },
    },

    collections: {
      steps: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
        }
      },
      benefits: {
        requirement: "optional",
        fillMode: "ai_generated_needs_review",
        constraints: { min: 0, max: 3 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated_needs_review", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  PropertyComparisonMatrix: {
    sectionType: "PropertyComparisonMatrix",

    elements: {
      headline:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "How We Compare" },
      subheadline:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      feature_header:     { type: "string", requirement: "required", fillMode: "ai_generated", default: "Feature" },
      us_header:          { type: "string", requirement: "required", fillMode: "ai_generated", default: "Us" },
      competitors_header: { type: "string", requirement: "required", fillMode: "ai_generated", default: "Competitors" },
      footer_text:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      comparison_rows: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 8 },
        fields: {
          id:               { type: "string", fillMode: "system" },
          property:         { type: "string", fillMode: "ai_generated", default: "" },
          us_value:         { type: "string", fillMode: "ai_generated", default: "" },
          competitor_value: { type: "string", fillMode: "ai_generated", default: "" },
        }
      }
    }
  },

  SecretSauceReveal: {
    sectionType: "SecretSauceReveal",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Our Secret Sauce Revealed" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      secrets: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 4 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // UniqueMechanism Section - StackedHighlights (V2 Schema)
  StackedHighlights: {
    sectionType: "StackedHighlights",

    elements: {
      headline:       { type: "string", requirement: "required", fillMode: "ai_generated", default: "Our Proprietary SmartFlow System™" },
      subheadline:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Three unique capabilities that set us apart." },
      mechanism_name: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      footer_text:    { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Our proprietary approach that you won't find anywhere else" },
    },

    collections: {
      highlights: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // TechnicalAdvantage - V2 Schema
  TechnicalAdvantage: {
    sectionType: "TechnicalAdvantage",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Technical Advantages That Set Us Apart" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      advantages: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          title:       { type: "string", fillMode: "ai_generated", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // UseCase Section - V2 Schema
  IndustryUseCaseGrid: {
    sectionType: "IndustryUseCaseGrid",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Trusted Across Industries" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      industries: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 4, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          name:        { type: "string", fillMode: "ai_generated", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  // PersonaGrid - V2 Schema
  PersonaGrid: {
    sectionType: "PersonaGrid",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Built for Every Team Member" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      footer_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      personas: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 2, max: 6 },
        fields: {
          id:          { type: "string", fillMode: "system" },
          name:        { type: "string", fillMode: "ai_generated", default: "" },
          description: { type: "string", fillMode: "ai_generated", default: "" },
          icon:        { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },

  RoleBasedScenarios: {
    sectionType: "RoleBasedScenarios",

    elements: {
      headline:    { type: "string", requirement: "required", fillMode: "ai_generated", default: "Perfect for Every Role" },
      subheadline: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      footer_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
    },

    collections: {
      scenarios: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 6 },
        fields: {
          id:       { type: "string", fillMode: "system" },
          role:     { type: "string", fillMode: "ai_generated", default: "" },
          scenario: { type: "string", fillMode: "ai_generated", default: "" },
        }
      }
    }
  },

  // CTA Section - V2 Schema
  CenteredHeadlineCTA: {
    sectionType: "CenteredHeadlineCTA",

    elements: {
      // Required AI-generated
      headline:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Ready to Transform Your Business?" },
      cta_text:           { type: "string", requirement: "required", fillMode: "ai_generated", default: "Start Your Free Trial Today" },

      // Optional AI-generated
      subheadline:        { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Join thousands of companies already using our platform to streamline operations and boost productivity." },
      secondary_cta_text: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      urgency_text:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },

      // AI-generated needs review (user should verify these stats)
      customer_count:     { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "10,000+" },
      customer_label:     { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "Happy customers" },
      rating_stat:        { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "4.8/5 stars" },
      uptime_stat:        { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "99.9% uptime" },
      uptime_label:       { type: "string", requirement: "optional", fillMode: "ai_generated_needs_review", default: "SOC 2 Compliant" },
    },

    collections: {
      trust_items: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated" },
        }
      }
    }
  },

  VisualCTAWithMockup: {
    sectionType: "VisualCTAWithMockup",

    elements: {
      headline:      { type: "string", requirement: "required", fillMode: "ai_generated", default: "See It in Action" },
      subheadline:   { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Experience the power of our platform with a live demo. No installation required." },
      cta_text:      { type: "string", requirement: "required", fillMode: "ai_generated", default: "Start Free Trial" },
      secondary_cta: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      urgency_text:  { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      mockup_image:  { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "" },
    },

    collections: {
      trust_items: {
        requirement: "optional",
        fillMode: "ai_generated",
        constraints: { min: 0, max: 5 },
        fields: {
          id:   { type: "string", fillMode: "system" },
          text: { type: "string", fillMode: "ai_generated" },
        }
      }
    }
  },

  ValueStackCTA: {
    sectionType: "ValueStackCTA",

    elements: {
      headline:             { type: "string", requirement: "required", fillMode: "ai_generated", default: "Everything You Get With Your Account" },
      subheadline:          { type: "string", requirement: "optional", fillMode: "ai_generated", default: "One subscription, unlimited value" },
      cta_text:             { type: "string", requirement: "required", fillMode: "ai_generated", default: "Start Free Trial" },
      secondary_cta_text:   { type: "string", requirement: "optional", fillMode: "ai_generated", default: "" },
      final_cta_headline:   { type: "string", requirement: "required", fillMode: "ai_generated", default: "Ready to Transform Your Workflow?" },
      final_cta_description:{ type: "string", requirement: "required", fillMode: "ai_generated", default: "Join 10,000+ teams already saving time every day" },
      guarantee_text:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "30-day money-back guarantee" },
    },

    collections: {
      value_items: {
        requirement: "required",
        fillMode: "ai_generated",
        constraints: { min: 3, max: 8 },
        fields: {
          id:    { type: "string", fillMode: "system" },
          text:  { type: "string", fillMode: "ai_generated", default: "" }
        }
      }
    }
  },

  // Header Section - V2 Schema
  // Note: Navigation is managed via store.navigationConfig, schema is reference only
  MinimalNavHeader: {
    sectionType: "MinimalNavHeader",

    elements: {
      // Logo from globalSettings.logoUrl, not stored in section content
    },

    collections: {
      nav_items: {
        requirement: "optional",
        fillMode: "manual_preferred",
        constraints: { min: 0, max: 4 },
        fields: {
          id:    { type: "string", fillMode: "system" },
          label: { type: "string", fillMode: "manual_preferred", default: "Link" },
          link:  { type: "string", fillMode: "manual_preferred", default: "#" },
        }
      }
    }
  },

  // Footer Section - V2 Schema
  ContactFooter: {
    sectionType: "ContactFooter",

    elements: {
      footer_style:           { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "dark" },
      copyright:              { type: "string", requirement: "required", fillMode: "manual_preferred", default: "© 2025 Your Company. All rights reserved." },
      newsletter_title:       { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Stay Updated" },
      newsletter_description: { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Get the latest updates and news delivered to your inbox." },
      newsletter_cta:         { type: "string", requirement: "optional", fillMode: "ai_generated", default: "Subscribe" },
      email:                  { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "contact@company.com" },
      phone:                  { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "+1 (555) 123-4567" },
      address:                { type: "string", requirement: "optional", fillMode: "manual_preferred", default: "123 Business St, Suite 100, City, State 12345" },
    },

    collections: {
      social_links: {
        requirement: "optional",
        fillMode: "manual_preferred",
        constraints: { min: 0, max: 8 },
        fields: {
          id:       { type: "string", fillMode: "system" },
          platform: { type: "string", fillMode: "manual_preferred" },
          url:      { type: "string", fillMode: "manual_preferred" },
          icon:     { type: "string", fillMode: "manual_preferred" },
        }
      }
    }
  },
}

/**
 * Sanitize content for publish: apply 4-case gating per section.
 * Strips excluded elements, sets defaults for missing required ones.
 * Mutates content in place.
 */
export function sanitizeContentForPublish(content: Record<string, any>): void {
  const sections: string[] = content?.layout?.sections;
  if (!sections || !Array.isArray(sections)) return;

  // Handle nested format (content.content[sectionId]) or flat (content[sectionId])
  const container = content.content && typeof content.content === 'object'
    ? content.content
    : content;

  for (const sectionId of sections) {
    const section = container[sectionId];
    if (!section?.elements || !section?.layout) continue;

    const schema = layoutElementSchema[section.layout];
    if (!schema || !isV2Schema(schema)) continue;

    const excludedArr: string[] = section.aiMetadata?.excludedElements || [];
    const excludedSet = new Set(excludedArr);

    // Expand toggleGroup children into excluded set
    for (const [key, def] of Object.entries(schema.elements)) {
      if (def.toggleGroup && excludedSet.has(def.toggleGroup)) {
        excludedSet.add(key);
      }
    }

    const elements = section.elements;
    const sanitized: Record<string, any> = {};

    // Gate elements
    for (const [key, def] of Object.entries(schema.elements)) {
      if (excludedSet.has(key)) continue;
      if (elements[key] !== undefined && elements[key] !== null) {
        sanitized[key] = elements[key];
      } else if (def.requirement === 'required') {
        sanitized[key] = def.default ?? '';
      }
    }

    // Gate collections
    if (schema.collections) {
      for (const [colName, colDef] of Object.entries(schema.collections)) {
        if (excludedSet.has(colName)) continue;
        if (colDef.toggleGroup && excludedSet.has(colDef.toggleGroup)) continue;

        if (elements[colName] !== undefined && elements[colName] !== null) {
          sanitized[colName] = elements[colName];
        } else if (colDef.requirement === 'required') {
          sanitized[colName] = [];
        }
      }
    }

    // Preserve non-schema keys
    const schemaKeys = new Set([
      ...Object.keys(schema.elements),
      ...Object.keys(schema.collections || {})
    ]);
    for (const [key, val] of Object.entries(elements)) {
      if (!schemaKeys.has(key)) {
        sanitized[key] = val;
      }
    }

    section.elements = sanitized;
  }
}
