interface LayoutElement {
  element: string;
  mandatory: boolean;
}

interface LayoutSchema {
  [layoutName: string]: LayoutElement[];
}

export const layoutElementSchema: LayoutSchema = {
  // BeforeAfter Section
  SideBySideBlocks: [
    { element: "headline", mandatory: true },
    { element: "before_label", mandatory: true },
    { element: "after_label", mandatory: true },
    { element: "before_description", mandatory: true },
    { element: "after_description", mandatory: true },
    { element: "before_icon", mandatory: false },
    { element: "after_icon", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  StackedTextVisual: [
    { element: "headline", mandatory: true },
    { element: "before_text", mandatory: true },
    { element: "after_text", mandatory: true },
    { element: "transition_text", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  BeforeAfterSlider: [
    { element: "headline", mandatory: true },
    { element: "before_label", mandatory: true },
    { element: "after_label", mandatory: true },
    { element: "before_description", mandatory: true },
    { element: "after_description", mandatory: true },
    { element: "before_visual", mandatory: false },
    { element: "after_visual", mandatory: false },
    { element: "before_placeholder_text", mandatory: false },
    { element: "after_placeholder_text", mandatory: false },
    { element: "interaction_hint_text", mandatory: false },
    { element: "show_interaction_hint", mandatory: false },
    { element: "before_icon", mandatory: false },
    { element: "after_icon", mandatory: false },
    { element: "hint_icon", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "slider_instruction", mandatory: false },
  ],

  SplitCard: [
    { element: "headline", mandatory: true },
    { element: "before_title", mandatory: true },
    { element: "after_title", mandatory: true },
    { element: "before_description", mandatory: true },
    { element: "after_description", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  TextListTransformation: [
    { element: "headline", mandatory: true },
    { element: "before_label", mandatory: true },
    { element: "after_label", mandatory: true },
    { element: "before_list", mandatory: true },
    { element: "after_list", mandatory: true },
    { element: "transformation_text", mandatory: false },
    { element: "before_icon", mandatory: false },
    { element: "after_icon", mandatory: false },
    { element: "transformation_icon", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  VisualStoryline: [
    { element: "headline", mandatory: true },
    { element: "story_steps", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "conclusion_text", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  // Results Section
  StatBlocks: [
    { element: "headline", mandatory: true },
    { element: "stat_values", mandatory: true },
    { element: "stat_labels", mandatory: true },
    { element: "stat_descriptions", mandatory: false },
    { element: "subheadline", mandatory: false },
  ],

  BeforeAfterStats: [
    { element: "headline", mandatory: true },
    { element: "before_stats", mandatory: true },
    { element: "after_stats", mandatory: true },
    { element: "stat_labels", mandatory: true },
    { element: "improvement_labels", mandatory: false },
  ],

  QuoteWithMetric: [
    { element: "headline", mandatory: true },
    { element: "result_quotes", mandatory: true },
    { element: "metric_values", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "customer_titles", mandatory: false },
  ],

  EmojiOutcomeGrid: [
    { element: "headline", mandatory: true },
    { element: "emojis", mandatory: true },
    { element: "outcomes", mandatory: true },
    { element: "descriptions", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "footer_text", mandatory: false },
  ],

  TimelineResults: [
    { element: "headline", mandatory: true },
    { element: "timeline_periods", mandatory: true },
    { element: "result_descriptions", mandatory: true },
    { element: "milestone_markers", mandatory: false },
  ],

  OutcomeIcons: [
    { element: "headline", mandatory: true },
    { element: "outcome_titles", mandatory: true },
    { element: "outcome_descriptions", mandatory: true },
    { element: "icon_labels", mandatory: false },
  ],

  StackedWinsList: [
    { element: "headline", mandatory: true },
    { element: "win_statements", mandatory: true },
    { element: "win_descriptions", mandatory: false },
    { element: "category_labels", mandatory: false },
  ],

  PersonaResultPanels: [
    { element: "headline", mandatory: true },
    { element: "personas", mandatory: true },
    { element: "roles", mandatory: true },
    { element: "result_metrics", mandatory: true },
    { element: "result_descriptions", mandatory: true },
    { element: "key_benefits", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "footer_text", mandatory: false },
    { element: "persona_icon_1", mandatory: false },
    { element: "persona_icon_2", mandatory: false },
    { element: "persona_icon_3", mandatory: false },
    { element: "persona_icon_4", mandatory: false },
    { element: "persona_icon_5", mandatory: false },
    { element: "persona_icon_6", mandatory: false },
  ],

  // Security Section
  // Security Section - Using actual component names
  AuditResultsPanel: [
    { element: "headline", mandatory: true },
    { element: "audit_titles", mandatory: true },
    { element: "audit_descriptions", mandatory: true },
    { element: "auditor_names", mandatory: true },
    { element: "audit_dates", mandatory: false },
  ],

  PenetrationTestResults: [
    { element: "headline", mandatory: true },
    { element: "test_categories", mandatory: true },
    { element: "test_results", mandatory: true },
    { element: "test_descriptions", mandatory: false },
    { element: "test_dates", mandatory: false },
  ],

  PrivacyCommitmentBlock: [
    { element: "headline", mandatory: true },
    { element: "policy_titles", mandatory: true },
    { element: "policy_summaries", mandatory: true },
    { element: "policy_details", mandatory: false },
    { element: "expand_labels", mandatory: false },
  ],

  SecurityChecklist: [
    { element: "headline", mandatory: true },
    { element: "security_items", mandatory: true },
    { element: "item_descriptions", mandatory: false },
    { element: "compliance_note", mandatory: false },
  ],

  SecurityGuaranteePanel: [
    { element: "headline", mandatory: true },
    { element: "security_stats", mandatory: true },
    { element: "stat_labels", mandatory: true },
    { element: "stat_descriptions", mandatory: false },
  ],

  TrustSealCollection: [
    { element: "headline", mandatory: true },
    { element: "compliance_names", mandatory: true },
    { element: "badge_descriptions", mandatory: false },
    { element: "subheadline", mandatory: false },
  ],

  // SocialProof Section
  LogoWall: [
    { element: "headline", mandatory: true },
    { element: "company_names", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "category_labels", mandatory: false },
  ],

  MediaMentions: [
    { element: "headline", mandatory: true },
    { element: "media_names", mandatory: true },
    { element: "mention_quotes", mandatory: true },
    { element: "mention_dates", mandatory: false },
  ],

  UserCountBar: [
    { element: "headline", mandatory: true },
    { element: "user_count", mandatory: true },
    { element: "count_description", mandatory: true },
    { element: "growth_stats", mandatory: false },
  ],

  IndustryBadgeLine: [
    { element: "headline", mandatory: true },
    { element: "badge_titles", mandatory: true },
    { element: "badge_descriptions", mandatory: false },
    { element: "industry_context", mandatory: false },
  ],

  MapHeatSpots: [
    { element: "headline", mandatory: true },
    { element: "location_names", mandatory: true },
    { element: "usage_stats", mandatory: true },
    { element: "map_legend", mandatory: false },
  ],

  StackedStats: [
    { element: "headline", mandatory: true },
    { element: "stat_values", mandatory: true },
    { element: "stat_labels", mandatory: true },
    { element: "stat_contexts", mandatory: false },
  ],

  StripWithReviews: [
    { element: "headline", mandatory: true },
    { element: "review_snippets", mandatory: true },
    { element: "review_sources", mandatory: true },
    { element: "rating_scores", mandatory: false },
  ],

  SocialProofStrip: [
    { element: "headline", mandatory: true },
    { element: "proof_statements", mandatory: true },
    { element: "proof_sources", mandatory: true },
    { element: "credibility_markers", mandatory: false },
  ],

  // Testimonial Section
  QuoteGrid: [
    { element: "headline", mandatory: true },
    { element: "testimonial_quotes", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "customer_titles", mandatory: false },
    { element: "customer_companies", mandatory: false },
  ],

  VideoTestimonials: [
    { element: "headline", mandatory: true },
    { element: "video_titles", mandatory: true },
    { element: "video_descriptions", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "customer_titles", mandatory: false },
  ],

  AvatarCarousel: [
    { element: "headline", mandatory: true },
    { element: "testimonial_quotes", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "customer_titles", mandatory: false },
    { element: "carousel_navigation", mandatory: false },
  ],

  BeforeAfterQuote: [
    { element: "headline", mandatory: true },
    { element: "before_quotes", mandatory: true },
    { element: "after_quotes", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "transformation_labels", mandatory: false },
  ],

  SegmentedTestimonials: [
    { element: "headline", mandatory: true },
    { element: "segment_labels", mandatory: true },
    { element: "testimonial_quotes", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "customer_titles", mandatory: false },
  ],

  RatingCards: [
    { element: "headline", mandatory: true },
    { element: "testimonial_quotes", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "customer_titles", mandatory: true },
    { element: "ratings", mandatory: true },
    { element: "review_platforms", mandatory: true },
    { element: "review_dates", mandatory: false },
    { element: "verified_badges", mandatory: false },
    { element: "customer_locations", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  PullQuoteStack: [
    { element: "headline", mandatory: true },
    { element: "pullquote_texts", mandatory: true },
    { element: "quote_attributions", mandatory: true },
    { element: "quote_contexts", mandatory: false },
  ],

  InteractiveTestimonialMap: [
    { element: "headline", mandatory: true },
    { element: "location_markers", mandatory: true },
    { element: "testimonial_quotes", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "location_labels", mandatory: false },
  ],

  // UniqueMechanism Section - Updated to match actual component implementations
  AlgorithmExplainer: [
    { element: "headline", mandatory: true },
    { element: "algorithm_name", mandatory: true },
    { element: "algorithm_steps", mandatory: false }, // Legacy pipe-separated format
    { element: "algorithm_step_1", mandatory: true },
    { element: "algorithm_step_2", mandatory: true },
    { element: "algorithm_step_3", mandatory: true },
    { element: "algorithm_step_4", mandatory: false },
    { element: "algorithm_step_5", mandatory: false },
    { element: "algorithm_step_6", mandatory: false },
    { element: "algorithm_step_7", mandatory: false },
    { element: "algorithm_step_8", mandatory: false },
  ],

  InnovationTimeline: [
    { element: "headline", mandatory: true },
    { element: "timeline_items", mandatory: false }, // Legacy pipe-separated format
    { element: "timeline_item_1", mandatory: true },
    { element: "timeline_item_2", mandatory: true },
    { element: "timeline_item_3", mandatory: true },
    { element: "timeline_item_4", mandatory: false },
    { element: "timeline_item_5", mandatory: false },
    { element: "timeline_item_6", mandatory: false },
  ],

  MethodologyBreakdown: [
    { element: "headline", mandatory: true },
    { element: "methodology_name", mandatory: true },
    { element: "methodology_description", mandatory: true },
    { element: "principle_1", mandatory: true },
    { element: "principle_2", mandatory: true },
    { element: "principle_3", mandatory: true },
    { element: "principle_4", mandatory: false },
    { element: "principle_5", mandatory: false },
    { element: "principle_6", mandatory: false },
    { element: "detail_1", mandatory: true },
    { element: "detail_2", mandatory: true },
    { element: "detail_3", mandatory: true },
    { element: "detail_4", mandatory: false },
    { element: "detail_5", mandatory: false },
    { element: "detail_6", mandatory: false },
    { element: "result_metric_1", mandatory: false },
    { element: "result_metric_2", mandatory: false },
    { element: "result_metric_3", mandatory: false },
    { element: "result_metric_4", mandatory: false },
    { element: "result_label_1", mandatory: false },
    { element: "result_label_2", mandatory: false },
    { element: "result_label_3", mandatory: false },
    { element: "result_label_4", mandatory: false },
    { element: "results_title", mandatory: false },
    { element: "methodology_icon", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "key_principles", mandatory: false },
    { element: "principle_details", mandatory: false },
    { element: "result_metrics", mandatory: false },
    { element: "result_labels", mandatory: false },
  ],

  ProcessFlowDiagram: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "process_steps", mandatory: true }, // Pipe-separated format
    { element: "step_descriptions", mandatory: true }, // Pipe-separated format
    { element: "benefits_title", mandatory: false },
    { element: "benefit_titles", mandatory: false },
    { element: "benefit_descriptions", mandatory: false },
    { element: "benefit_icon_1", mandatory: false },
    { element: "benefit_icon_2", mandatory: false },
    { element: "benefit_icon_3", mandatory: false },
  ],

  PropertyComparisonMatrix: [
    { element: "headline", mandatory: true },
    { element: "properties", mandatory: true }, // Pipe-separated format
    { element: "us_values", mandatory: true }, // Pipe-separated format
    { element: "competitors_values", mandatory: true }, // Pipe-separated format
    { element: "feature_header", mandatory: true },
    { element: "us_header", mandatory: true },
    { element: "competitors_header", mandatory: true },
  ],

  SecretSauceReveal: [
    { element: "headline", mandatory: true },
    { element: "secret_sauce", mandatory: true },
    { element: "explanation", mandatory: true },
    { element: "secret_icon", mandatory: false },
  ],

  StackedHighlights: [
    { element: "headline", mandatory: true },
    { element: "highlight_titles", mandatory: true }, // Pipe-separated format
    { element: "highlight_descriptions", mandatory: true }, // Pipe-separated format
    { element: "mechanism_name", mandatory: false },
    { element: "footer_text", mandatory: false },
    { element: "highlight_icon_1", mandatory: false },
    { element: "highlight_icon_2", mandatory: false },
    { element: "highlight_icon_3", mandatory: false },
    { element: "highlight_icon_4", mandatory: false },
    { element: "highlight_icon_5", mandatory: false },
    { element: "highlight_icon_6", mandatory: false },
  ],

  SystemArchitecture: [
    { element: "headline", mandatory: true },
    { element: "architecture_components", mandatory: false }, // Legacy pipe-separated format
    { element: "component_1", mandatory: true },
    { element: "component_2", mandatory: true },
    { element: "component_3", mandatory: true },
    { element: "component_4", mandatory: false },
    { element: "component_5", mandatory: false },
    { element: "component_6", mandatory: false },
    { element: "component_icon_1", mandatory: false },
    { element: "component_icon_2", mandatory: false },
    { element: "component_icon_3", mandatory: false },
    { element: "component_icon_4", mandatory: false },
    { element: "component_icon_5", mandatory: false },
    { element: "component_icon_6", mandatory: false },
  ],

  TechnicalAdvantage: [
    { element: "headline", mandatory: true },
    { element: "advantages", mandatory: true }, // Pipe-separated format
    { element: "advantage_descriptions", mandatory: false }, // Pipe-separated format
    { element: "advantage_icon_1", mandatory: false },
    { element: "advantage_icon_2", mandatory: false },
    { element: "advantage_icon_3", mandatory: false },
    { element: "advantage_icon_4", mandatory: false },
    { element: "advantage_icon_5", mandatory: false },
    { element: "advantage_icon_6", mandatory: false },
  ],

  // UseCase Section - Using actual component names
  BeforeAfterWorkflow: [
    { element: "headline", mandatory: true },
    { element: "workflow_steps", mandatory: true },
    { element: "before_descriptions", mandatory: true },
    { element: "after_descriptions", mandatory: true },
    { element: "workflow_benefits", mandatory: false },
  ],

  CustomerJourneyFlow: [
    { element: "headline", mandatory: true },
    { element: "journey_stages", mandatory: true },
    { element: "stage_descriptions", mandatory: true },
    { element: "stage_outcomes", mandatory: false },
  ],

  IndustryUseCaseGrid: [
    { element: "headline", mandatory: true },
    { element: "industry_names", mandatory: true },
    { element: "industry_descriptions", mandatory: true },
    { element: "industry_examples", mandatory: false },
  ],

  InteractiveUseCaseMap: [
    { element: "headline", mandatory: true },
    { element: "use_case_categories", mandatory: true },
    { element: "use_case_descriptions", mandatory: true },
    { element: "interaction_labels", mandatory: false },
  ],

  PersonaGrid: [
    { element: "headline", mandatory: true },
    { element: "persona_names", mandatory: true },
    { element: "persona_descriptions", mandatory: true },
    { element: "use_case_examples", mandatory: false },
  ],

  RoleBasedScenarios: [
    { element: "headline", mandatory: true },
    { element: "role_names", mandatory: true },
    { element: "scenario_descriptions", mandatory: true },
    { element: "scenario_outcomes", mandatory: false },
  ],

  UseCaseCarousel: [
    { element: "headline", mandatory: true },
    { element: "use_case_titles", mandatory: true },
    { element: "use_case_descriptions", mandatory: true },
    { element: "carousel_navigation", mandatory: false },
  ],

  WorkflowDiagrams: [
    { element: "headline", mandatory: true },
    { element: "workflow_steps", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "diagram_labels", mandatory: false },
  ],

  JobToBeDoneList: [
    { element: "headline", mandatory: true },
    { element: "job_titles", mandatory: true },
    { element: "job_descriptions", mandatory: true },
    { element: "solution_approaches", mandatory: false },
  ],

  StatComparison: [
    { element: "headline", mandatory: true },
    { element: "before_label", mandatory: true },
    { element: "after_label", mandatory: true },
    { element: "before_stats", mandatory: true },
    { element: "after_stats", mandatory: true },
    { element: "improvement_text", mandatory: false },
    { element: "summary_title", mandatory: false },
    { element: "summary_stat_1_value", mandatory: false },
    { element: "summary_stat_1_label", mandatory: false },
    { element: "summary_stat_2_value", mandatory: false },
    { element: "summary_stat_2_label", mandatory: false },
    { element: "summary_stat_3_value", mandatory: false },
    { element: "summary_stat_3_label", mandatory: false },
    { element: "show_summary_section", mandatory: false },
    { element: "improvement_icon", mandatory: false },
    { element: "flow_icon", mandatory: false },
    { element: "stat_icon_1", mandatory: false },
    { element: "stat_icon_2", mandatory: false },
    { element: "stat_icon_3", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  PersonaJourney: [
    { element: "headline", mandatory: true },
    { element: "persona_name", mandatory: true },
    { element: "before_scenario", mandatory: true },
    { element: "after_scenario", mandatory: true },
    { element: "journey_steps", mandatory: false },
    { element: "persona_quote", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  // Close Section
  MockupWithCTA: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "urgency_text", mandatory: false },
    { element: "guarantee_text", mandatory: false },
  ],

  BonusStackCTA: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "bonus_items", mandatory: true },
    { element: "total_value_text", mandatory: false },
    { element: "urgency_text", mandatory: false },
  ],

  LeadMagnetCard: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "magnet_title", mandatory: true },
    { element: "magnet_description", mandatory: true },
    { element: "form_labels", mandatory: false },
    { element: "privacy_text", mandatory: false },
  ],

  EnterpriseContactBox: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "contact_description", mandatory: true },
    { element: "features_list", mandatory: false },
    { element: "contact_methods", mandatory: false },
  ],

  ValueReinforcementBlock: [
    { element: "headline", mandatory: true },
    { element: "value_points", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "closing_statement", mandatory: false },
  ],

  LivePreviewEmbed: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "preview_description", mandatory: true },
    { element: "instruction_text", mandatory: false },
  ],

  SideBySideOfferCards: [
    { element: "headline", mandatory: true },
    { element: "offer_titles", mandatory: true },
    { element: "offer_descriptions", mandatory: true },
    { element: "cta_texts", mandatory: true },
    { element: "comparison_points", mandatory: false },
  ],

  MultistepCTAStack: [
    { element: "headline", mandatory: true },
    { element: "step_titles", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "final_cta_text", mandatory: true },
    { element: "progress_labels", mandatory: false },
  ],

  // Comparison Section
  BasicFeatureGrid: [
    { element: "headline", mandatory: true },
    { element: "feature_names", mandatory: true },
    { element: "competitor_names", mandatory: true },
    { element: "your_product_name", mandatory: true },
    { element: "subheadline", mandatory: false },
  ],

  CheckmarkComparison: [
    { element: "headline", mandatory: true },
    { element: "feature_list", mandatory: true },
    { element: "competitor_name", mandatory: true },
    { element: "your_product_name", mandatory: true },
    { element: "comparison_summary", mandatory: false },
  ],

  YouVsThemHighlight: [
    { element: "headline", mandatory: true },
    { element: "your_approach_title", mandatory: true },
    { element: "their_approach_title", mandatory: true },
    { element: "your_approach_description", mandatory: true },
    { element: "their_approach_description", mandatory: true },
    { element: "conclusion_text", mandatory: false },
  ],

  ToggleableComparison: [
    { element: "headline", mandatory: true },
    { element: "toggle_labels", mandatory: true },
    { element: "comparison_categories", mandatory: true },
    { element: "comparison_values", mandatory: true },
    { element: "subheadline", mandatory: false },
  ],

  CompetitorCallouts: [
    { element: "headline", mandatory: true },
    { element: "competitor_names", mandatory: true },
    { element: "callout_titles", mandatory: true },
    { element: "callout_descriptions", mandatory: true },
    { element: "your_advantage_text", mandatory: false },
  ],

  AnimatedUpgradePath: [
    { element: "headline", mandatory: true },
    { element: "stage_titles", mandatory: true },
    { element: "stage_descriptions", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "stage_icons", mandatory: false },
    { element: "stage_icon_1", mandatory: false },
    { element: "stage_icon_2", mandatory: false },
    { element: "stage_icon_3", mandatory: false },
    { element: "cta_text", mandatory: false },
  ],

  PersonaUseCaseCompare: [
    { element: "headline", mandatory: true },
    { element: "persona_names", mandatory: true },
    { element: "use_case_titles", mandatory: true },
    { element: "solution_descriptions", mandatory: true },
    { element: "outcome_comparisons", mandatory: false },
  ],

  LiteVsProVsEnterprise: [
    { element: "headline", mandatory: true },
    { element: "tier_names", mandatory: true },
    { element: "tier_descriptions", mandatory: true },
    { element: "feature_comparisons", mandatory: true },
    { element: "recommended_labels", mandatory: false },
  ],

  // FAQ Section
  AccordionFAQ: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual Q&A fields (up to 5 items)
    { element: "question_1", mandatory: true },
    { element: "answer_1", mandatory: true },
    { element: "question_2", mandatory: true },
    { element: "answer_2", mandatory: true },
    { element: "question_3", mandatory: true },
    { element: "answer_3", mandatory: true },
    { element: "question_4", mandatory: false },
    { element: "answer_4", mandatory: false },
    { element: "question_5", mandatory: false },
    { element: "answer_5", mandatory: false },
    // Icon fields
    { element: "expand_icon", mandatory: false },
    { element: "collapse_icon", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "questions", mandatory: false },
    { element: "answers", mandatory: false },
  ],

  TwoColumnFAQ: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Left column Q&A (up to 3 items)
    { element: "left_question_1", mandatory: true },
    { element: "left_answer_1", mandatory: true },
    { element: "left_question_2", mandatory: true },
    { element: "left_answer_2", mandatory: true },
    { element: "left_question_3", mandatory: false },
    { element: "left_answer_3", mandatory: false },
    // Right column Q&A (up to 3 items)
    { element: "right_question_1", mandatory: true },
    { element: "right_answer_1", mandatory: true },
    { element: "right_question_2", mandatory: true },
    { element: "right_answer_2", mandatory: true },
    { element: "right_question_3", mandatory: false },
    { element: "right_answer_3", mandatory: false },
    // Column configuration
    { element: "left_column_title", mandatory: false },
    { element: "right_column_title", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "questions", mandatory: false },
    { element: "answers", mandatory: false },
    { element: "column_titles", mandatory: false },
    { element: "questions_left", mandatory: false },
    { element: "answers_left", mandatory: false },
    { element: "questions_right", mandatory: false },
    { element: "answers_right", mandatory: false },
  ],

  InlineQnAList: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "question_1", mandatory: true },
    { element: "answer_1", mandatory: true },
    { element: "question_2", mandatory: true },
    { element: "answer_2", mandatory: true },
    { element: "question_3", mandatory: true },
    { element: "answer_3", mandatory: true },
    { element: "question_4", mandatory: false },
    { element: "answer_4", mandatory: false },
    { element: "question_5", mandatory: false },
    { element: "answer_5", mandatory: false },
    { element: "question_6", mandatory: false },
    { element: "answer_6", mandatory: false },
    { element: "questions", mandatory: false },
    { element: "answers", mandatory: false },
  ],

  SegmentedFAQTabs: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Tab configuration
    { element: "tab_1_label", mandatory: true },
    { element: "tab_2_label", mandatory: true },
    { element: "tab_3_label", mandatory: false },
    { element: "tab_1_description", mandatory: false },
    { element: "tab_2_description", mandatory: false },
    { element: "tab_3_description", mandatory: false },
    // Tab 1 Q&A (up to 3 items per tab)
    { element: "tab_1_question_1", mandatory: true },
    { element: "tab_1_answer_1", mandatory: true },
    { element: "tab_1_question_2", mandatory: false },
    { element: "tab_1_answer_2", mandatory: false },
    { element: "tab_1_question_3", mandatory: false },
    { element: "tab_1_answer_3", mandatory: false },
    // Tab 2 Q&A
    { element: "tab_2_question_1", mandatory: true },
    { element: "tab_2_answer_1", mandatory: true },
    { element: "tab_2_question_2", mandatory: false },
    { element: "tab_2_answer_2", mandatory: false },
    { element: "tab_2_question_3", mandatory: false },
    { element: "tab_2_answer_3", mandatory: false },
    // Tab 3 Q&A
    { element: "tab_3_question_1", mandatory: false },
    { element: "tab_3_answer_1", mandatory: false },
    { element: "tab_3_question_2", mandatory: false },
    { element: "tab_3_answer_2", mandatory: false },
    { element: "tab_3_question_3", mandatory: false },
    { element: "tab_3_answer_3", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "tab_labels", mandatory: false },
    { element: "tab_descriptions", mandatory: false },
    { element: "questions", mandatory: false },
    { element: "answers", mandatory: false },
  ],

  QuoteStyleAnswers: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual Q&A with quotes (up to 5 items)
    { element: "question_1", mandatory: true },
    { element: "quote_answer_1", mandatory: true },
    { element: "attribution_1", mandatory: true },
    { element: "question_2", mandatory: true },
    { element: "quote_answer_2", mandatory: true },
    { element: "attribution_2", mandatory: true },
    { element: "question_3", mandatory: false },
    { element: "quote_answer_3", mandatory: false },
    { element: "attribution_3", mandatory: false },
    { element: "question_4", mandatory: false },
    { element: "quote_answer_4", mandatory: false },
    { element: "attribution_4", mandatory: false },
    { element: "question_5", mandatory: false },
    { element: "quote_answer_5", mandatory: false },
    { element: "attribution_5", mandatory: false },
    // Style configuration
    { element: "quote_style", mandatory: false },
    { element: "attribution_style", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "questions", mandatory: false },
    { element: "quote_answers", mandatory: false },
    { element: "quote_attributions", mandatory: false },
  ],

  IconWithAnswers: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual Q&A with icons (up to 6 items)
    { element: "question_1", mandatory: true },
    { element: "answer_1", mandatory: true },
    { element: "icon_1", mandatory: true },
    { element: "question_2", mandatory: true },
    { element: "answer_2", mandatory: true },
    { element: "icon_2", mandatory: true },
    { element: "question_3", mandatory: true },
    { element: "answer_3", mandatory: true },
    { element: "icon_3", mandatory: true },
    { element: "question_4", mandatory: false },
    { element: "answer_4", mandatory: false },
    { element: "icon_4", mandatory: false },
    { element: "question_5", mandatory: false },
    { element: "answer_5", mandatory: false },
    { element: "icon_5", mandatory: false },
    { element: "question_6", mandatory: false },
    { element: "answer_6", mandatory: false },
    { element: "icon_6", mandatory: false },
    // Icon configuration
    { element: "icon_position", mandatory: false },
    { element: "icon_size", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "questions", mandatory: false },
    { element: "answers", mandatory: false },
    { element: "icon_labels", mandatory: false },
  ],

  TestimonialFAQs: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual Q&A with testimonials (up to 5 items)
    { element: "question_1", mandatory: true },
    { element: "testimonial_answer_1", mandatory: true },
    { element: "customer_name_1", mandatory: true },
    { element: "customer_title_1", mandatory: false },
    { element: "customer_company_1", mandatory: false },
    { element: "question_2", mandatory: true },
    { element: "testimonial_answer_2", mandatory: true },
    { element: "customer_name_2", mandatory: true },
    { element: "customer_title_2", mandatory: false },
    { element: "customer_company_2", mandatory: false },
    { element: "question_3", mandatory: false },
    { element: "testimonial_answer_3", mandatory: false },
    { element: "customer_name_3", mandatory: false },
    { element: "customer_title_3", mandatory: false },
    { element: "customer_company_3", mandatory: false },
    { element: "question_4", mandatory: false },
    { element: "testimonial_answer_4", mandatory: false },
    { element: "customer_name_4", mandatory: false },
    { element: "customer_title_4", mandatory: false },
    { element: "customer_company_4", mandatory: false },
    { element: "question_5", mandatory: false },
    { element: "testimonial_answer_5", mandatory: false },
    { element: "customer_name_5", mandatory: false },
    { element: "customer_title_5", mandatory: false },
    { element: "customer_company_5", mandatory: false },
    // Style configuration
    { element: "testimonial_style", mandatory: false },
    { element: "customer_photo_style", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "questions", mandatory: false },
    { element: "testimonial_answers", mandatory: false },
    { element: "customer_names", mandatory: false },
    { element: "customer_titles", mandatory: false },
  ],

  ChatBubbleFAQ: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual chat conversations (up to 5 items)
    { element: "question_1", mandatory: true },
    { element: "answer_1", mandatory: true },
    { element: "persona_1", mandatory: false },
    { element: "question_2", mandatory: true },
    { element: "answer_2", mandatory: true },
    { element: "persona_2", mandatory: false },
    { element: "question_3", mandatory: false },
    { element: "answer_3", mandatory: false },
    { element: "persona_3", mandatory: false },
    { element: "question_4", mandatory: false },
    { element: "answer_4", mandatory: false },
    { element: "persona_4", mandatory: false },
    { element: "question_5", mandatory: false },
    { element: "answer_5", mandatory: false },
    { element: "persona_5", mandatory: false },
    // Chat configuration
    { element: "customer_persona_name", mandatory: false },
    { element: "support_persona_name", mandatory: false },
    { element: "chat_style", mandatory: false },
    { element: "bubble_alignment", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "questions", mandatory: false },
    { element: "answers", mandatory: false },
    { element: "chat_personas", mandatory: false },
  ],

  // Features Section
  IconGrid: [
    { element: "headline", mandatory: true },
    { element: "feature_titles", mandatory: true },
    { element: "feature_descriptions", mandatory: true },
    { element: "subheadline", mandatory: false },
  ],

  SplitAlternating: [
    { element: "headline", mandatory: true },
    { element: "feature_titles", mandatory: true },
    { element: "feature_descriptions", mandatory: true },
    { element: "feature_benefits", mandatory: false },
  ],

  Tabbed: [
    { element: "headline", mandatory: true },
    { element: "tab_labels", mandatory: true },
    { element: "tab_titles", mandatory: true },
    { element: "tab_descriptions", mandatory: true },
    { element: "subheadline", mandatory: false },
  ],

  Timeline: [
    { element: "headline", mandatory: true },
    { element: "timeline_titles", mandatory: true },
    { element: "timeline_descriptions", mandatory: true },
    { element: "timeline_dates", mandatory: false },
    { element: "milestone_labels", mandatory: false },
  ],

  FeatureTestimonial: [
    { element: "headline", mandatory: true },
    { element: "feature_titles", mandatory: true },
    { element: "feature_descriptions", mandatory: true },
    { element: "testimonial_quotes", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "customer_titles", mandatory: false },
  ],

  MetricTiles: [
    { element: "headline", mandatory: true },
    { element: "metric_values", mandatory: true },
    { element: "metric_labels", mandatory: true },
    { element: "metric_descriptions", mandatory: false },
    { element: "subheadline", mandatory: false },
  ],

  MiniCards: [
    { element: "headline", mandatory: true },
    { element: "card_titles", mandatory: true },
    { element: "card_descriptions", mandatory: true },
    { element: "card_tags", mandatory: false },
  ],

  Carousel: [
    { element: "headline", mandatory: true },
    { element: "slide_titles", mandatory: true },
    { element: "slide_descriptions", mandatory: true },
    { element: "navigation_labels", mandatory: false },
    { element: "slide_numbers", mandatory: false },
  ],

  // FounderNote Section
  FounderCardWithQuote: [
    { element: "founder_name", mandatory: true },
    { element: "founder_title", mandatory: true },
    { element: "founder_quote", mandatory: true },
    { element: "founder_bio", mandatory: false },
    { element: "company_context", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "founder_image", mandatory: false },
  ],

  LetterStyleBlock: [
    { element: "letter_header", mandatory: true },
    { element: "letter_greeting", mandatory: true },
    { element: "letter_body", mandatory: true },
    { element: "letter_signature", mandatory: true },
    { element: "founder_title", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "founder_name", mandatory: false },
    { element: "company_name", mandatory: false },
    { element: "date_text", mandatory: false },
    { element: "ps_text", mandatory: false },
    { element: "founder_image", mandatory: false },
  ],

  VideoNoteWithTranscript: [
    { element: "headline", mandatory: true },
    { element: "video_intro", mandatory: true },
    { element: "transcript_text", mandatory: true },
    { element: "founder_name", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "video_url", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  MissionQuoteOverlay: [
    { element: "mission_quote", mandatory: true },
    { element: "founder_name", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "founder_title", mandatory: false },
    { element: "badge_text", mandatory: false },
    { element: "badge_icon", mandatory: false },
    { element: "mission_stats", mandatory: false },
    { element: "mission_stat_1", mandatory: false },
    { element: "mission_stat_2", mandatory: false },
    { element: "mission_stat_3", mandatory: false },
    { element: "mission_stat_4", mandatory: false },
    { element: "mission_year", mandatory: false },
    { element: "background_image", mandatory: false },
  ],

  TimelineToToday: [
    { element: "headline", mandatory: true },
    { element: "intro_text", mandatory: true },
    { element: "timeline_items", mandatory: true },
    { element: "current_milestone", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "founder_name", mandatory: false },
    { element: "company_name", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "current_state_heading", mandatory: false },
    { element: "timeline_icon_1", mandatory: false },
    { element: "timeline_icon_2", mandatory: false },
    { element: "timeline_icon_3", mandatory: false },
    { element: "timeline_icon_4", mandatory: false },
    { element: "timeline_icon_5", mandatory: false },
    { element: "timeline_icon_6", mandatory: false },
    { element: "current_state_icon", mandatory: false },
  ],

  SideBySidePhotoStory: [
    { element: "story_headline", mandatory: true },
    { element: "story_text", mandatory: true },
    { element: "story_quote", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "founder_name", mandatory: false },
    { element: "story_stats", mandatory: false },
    { element: "story_stat_1", mandatory: false },
    { element: "story_stat_2", mandatory: false },
    { element: "story_stat_3", mandatory: false },
    { element: "story_stat_4", mandatory: false },
    { element: "badge_text", mandatory: false },
    { element: "badge_icon", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "story_image", mandatory: false },
    { element: "secondary_image", mandatory: false },
    { element: "placeholder_icon_1", mandatory: false },
    { element: "placeholder_icon_2", mandatory: false },
  ],

  StoryBlockWithPullquote: [
    { element: "story_headline", mandatory: true },
    { element: "story_content", mandatory: true },
    { element: "pullquote_text", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "founder_name", mandatory: false },
    { element: "badge_text", mandatory: false },
    { element: "badge_icon", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "story_image", mandatory: false },
  ],

  FoundersBeliefStack: [
    { element: "beliefs_headline", mandatory: true },
    { element: "beliefs_intro", mandatory: true },
    { element: "belief_items", mandatory: true },
    { element: "commitment_text", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "founder_name", mandatory: false },
    { element: "founder_title", mandatory: false },
    { element: "company_values", mandatory: false },
    { element: "company_value_1", mandatory: false },
    { element: "company_value_2", mandatory: false },
    { element: "company_value_3", mandatory: false },
    { element: "company_value_4", mandatory: false },
    { element: "company_value_5", mandatory: false },
    { element: "values_heading", mandatory: false },
    { element: "show_company_values", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "founder_image", mandatory: false },
    { element: "belief_icon_1", mandatory: false },
    { element: "belief_icon_2", mandatory: false },
    { element: "belief_icon_3", mandatory: false },
    { element: "belief_icon_4", mandatory: false },
    { element: "belief_icon_5", mandatory: false },
    { element: "belief_icon_6", mandatory: false },
  ],

  // Hero Section
  leftCopyRightImage: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: true },
    { element: "supporting_text", mandatory: false },
    { element: "badge_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "hero_image", mandatory: true },
    { element: "customer_count", mandatory: false },
    { element: "rating_value", mandatory: false },
    { element: "rating_count", mandatory: false },
    { element: "show_social_proof", mandatory: false },
    { element: "show_customer_avatars", mandatory: false },
    { element: "avatar_count", mandatory: false },
    { element: "customer_names", mandatory: false },
    { element: "avatar_urls", mandatory: false },
  ],

  centerStacked: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: true },
    { element: "supporting_text", mandatory: false },
    { element: "secondary_cta_text", mandatory: false },
    { element: "badge_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "center_hero_image", mandatory: true },
    { element: "customer_count", mandatory: false },
    { element: "rating_value", mandatory: false },
    { element: "rating_count", mandatory: false },
    { element: "show_social_proof", mandatory: false },
    { element: "show_customer_avatars", mandatory: false },
    { element: "avatar_count", mandatory: false },
    { element: "customer_names", mandatory: false },
    { element: "avatar_urls", mandatory: false },
  ],

  splitScreen: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: true },
    { element: "supporting_text", mandatory: false },
    { element: "badge_text", mandatory: false },
    { element: "value_proposition", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "split_hero_image", mandatory: true },
    { element: "customer_count", mandatory: false },
    { element: "rating_value", mandatory: false },
    { element: "rating_count", mandatory: false },
    { element: "show_social_proof", mandatory: false },
    { element: "show_customer_avatars", mandatory: false },
    { element: "avatar_count", mandatory: false },
    { element: "customer_names", mandatory: false },
    { element: "avatar_urls", mandatory: false },
  ],

  imageFirst: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: true },
    { element: "supporting_text", mandatory: false },
    { element: "badge_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "image_first_hero_image", mandatory: true },
    { element: "customer_count", mandatory: false },
    { element: "rating_value", mandatory: false },
    { element: "rating_count", mandatory: false },
    { element: "show_social_proof", mandatory: false },
    { element: "show_customer_avatars", mandatory: false },
    { element: "avatar_count", mandatory: false },
    { element: "customer_names", mandatory: false },
    { element: "avatar_urls", mandatory: false },
  ],

  // HowItWorks Section
  ThreeStepHorizontal: [
    { element: "headline", mandatory: true },
    { element: "step_titles", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "step_numbers", mandatory: false },
    { element: "conclusion_text", mandatory: false },
  ],

  VerticalTimeline: [
    { element: "headline", mandatory: true },
    { element: "step_titles", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "timeline_connector_text", mandatory: false },
  ],

  IconCircleSteps: [
    { element: "headline", mandatory: true },
    { element: "step_titles", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "step_labels", mandatory: false },
  ],

  AccordionSteps: [
    { element: "headline", mandatory: true },
    { element: "step_titles", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "step_details", mandatory: false },
  ],

  CardFlipSteps: [
    { element: "headline", mandatory: true },
    { element: "step_titles", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "step_details", mandatory: false },
    { element: "flip_instruction", mandatory: false },
  ],

  VideoWalkthrough: [
    { element: "headline", mandatory: true },
    { element: "video_title", mandatory: true },
    { element: "video_description", mandatory: true },
    { element: "chapter_titles", mandatory: false },
    { element: "video_duration", mandatory: false },
  ],

  ZigzagImageSteps: [
    { element: "headline", mandatory: true },
    { element: "step_titles", mandatory: true },
    { element: "step_descriptions", mandatory: true },
    { element: "image_captions", mandatory: false },
  ],

  AnimatedProcessLine: [
    { element: "headline", mandatory: true },
    { element: "process_titles", mandatory: true },
    { element: "process_descriptions", mandatory: true },
    { element: "animation_labels", mandatory: false },
  ],

  // Integration Section
  LogoGrid: [
    { element: "headline", mandatory: true },
    { element: "integration_names", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "category_labels", mandatory: false },
  ],

  CategoryAccordion: [
    { element: "headline", mandatory: true },
    { element: "category_titles", mandatory: true },
    { element: "integration_names", mandatory: true },
    { element: "category_descriptions", mandatory: false },
  ],

  InteractiveStackDiagram: [
    { element: "headline", mandatory: true },
    { element: "layer_titles", mandatory: true },
    { element: "layer_descriptions", mandatory: true },
    { element: "interaction_labels", mandatory: false },
  ],

  UseCaseTiles: [
    { element: "headline", mandatory: true },
    { element: "use_case_titles", mandatory: true },
    { element: "use_case_descriptions", mandatory: true },
    { element: "integration_lists", mandatory: false },
  ],

  BadgeCarousel: [
    { element: "headline", mandatory: true },
    { element: "badge_titles", mandatory: true },
    { element: "badge_descriptions", mandatory: true },
    { element: "carousel_navigation", mandatory: false },
  ],

  TabbyIntegrationCards: [
    { element: "headline", mandatory: true },
    { element: "tab_labels", mandatory: true },
    { element: "integration_titles", mandatory: true },
    { element: "integration_descriptions", mandatory: true },
    { element: "setup_instructions", mandatory: false },
  ],

  ZapierLikeBuilderPreview: [
    { element: "headline", mandatory: true },
    { element: "trigger_labels", mandatory: true },
    { element: "action_labels", mandatory: true },
    { element: "connection_descriptions", mandatory: true },
    { element: "builder_instructions", mandatory: false },
  ],

  LogoWithQuoteUse: [
    { element: "headline", mandatory: true },
    { element: "integration_names", mandatory: true },
    { element: "usage_quotes", mandatory: true },
    { element: "customer_names", mandatory: true },
    { element: "customer_titles", mandatory: false },
  ],

  // Objection Section
  ObjectionAccordion: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual objection fields (up to 6 items)
    { element: "objection_1", mandatory: true },
    { element: "response_1", mandatory: true },
    { element: "objection_2", mandatory: true },
    { element: "response_2", mandatory: true },
    { element: "objection_3", mandatory: true },
    { element: "response_3", mandatory: true },
    { element: "objection_4", mandatory: false },
    { element: "response_4", mandatory: false },
    { element: "objection_5", mandatory: false },
    { element: "response_5", mandatory: false },
    { element: "objection_6", mandatory: false },
    { element: "response_6", mandatory: false },
    // Icon fields
    { element: "objection_icon_1", mandatory: false },
    { element: "objection_icon_2", mandatory: false },
    { element: "objection_icon_3", mandatory: false },
    { element: "objection_icon_4", mandatory: false },
    { element: "objection_icon_5", mandatory: false },
    { element: "objection_icon_6", mandatory: false },
    // Global settings
    { element: "response_icon", mandatory: false },
    { element: "trust_icon", mandatory: false },
    { element: "help_text", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "objection_titles", mandatory: false },
    { element: "objection_responses", mandatory: false },
    { element: "objection_icons", mandatory: false },
  ],

  MythVsRealityGrid: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual myth/reality fields (up to 6 pairs)
    { element: "myth_1", mandatory: true },
    { element: "reality_1", mandatory: true },
    { element: "myth_2", mandatory: true },
    { element: "reality_2", mandatory: true },
    { element: "myth_3", mandatory: false },
    { element: "reality_3", mandatory: false },
    { element: "myth_4", mandatory: false },
    { element: "reality_4", mandatory: false },
    { element: "myth_5", mandatory: false },
    { element: "reality_5", mandatory: false },
    { element: "myth_6", mandatory: false },
    { element: "reality_6", mandatory: false },
    // Global icons
    { element: "myth_icon", mandatory: false },
    { element: "reality_icon", mandatory: false },
    // Legacy field for backward compatibility
    { element: "myth_reality_pairs", mandatory: false },
  ],

  QuoteBackedAnswers: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual objection/quote/attribution triplets (up to 6 items)
    { element: "objection_1", mandatory: true },
    { element: "quote_response_1", mandatory: true },
    { element: "quote_attribution_1", mandatory: true },
    { element: "objection_2", mandatory: true },
    { element: "quote_response_2", mandatory: true },
    { element: "quote_attribution_2", mandatory: true },
    { element: "objection_3", mandatory: false },
    { element: "quote_response_3", mandatory: false },
    { element: "quote_attribution_3", mandatory: false },
    { element: "objection_4", mandatory: false },
    { element: "quote_response_4", mandatory: false },
    { element: "quote_attribution_4", mandatory: false },
    { element: "objection_5", mandatory: false },
    { element: "quote_response_5", mandatory: false },
    { element: "quote_attribution_5", mandatory: false },
    { element: "objection_6", mandatory: false },
    { element: "quote_response_6", mandatory: false },
    { element: "quote_attribution_6", mandatory: false },
    // Source credibility and styling
    { element: "source_credentials", mandatory: false },
    { element: "expert_label", mandatory: false },
    { element: "verification_label", mandatory: false },
    { element: "trust_indicator_1", mandatory: false },
    { element: "trust_indicator_2", mandatory: false },
    { element: "trust_indicator_3", mandatory: false },
    { element: "quote_icon", mandatory: false },
    { element: "verification_icon", mandatory: false },
    { element: "trust_icon_1", mandatory: false },
    { element: "trust_icon_2", mandatory: false },
    { element: "trust_icon_3", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "objection_titles", mandatory: false },
    { element: "quote_responses", mandatory: false },
    { element: "quote_attributions", mandatory: false },
    { element: "quote_blocks", mandatory: false },
  ],

  VisualObjectionTiles: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual tile fields (up to 6 tiles)
    { element: "tile_objection_1", mandatory: true },
    { element: "tile_response_1", mandatory: true },
    { element: "tile_label_1", mandatory: false },
    { element: "tile_objection_2", mandatory: true },
    { element: "tile_response_2", mandatory: true },
    { element: "tile_label_2", mandatory: false },
    { element: "tile_objection_3", mandatory: true },
    { element: "tile_response_3", mandatory: true },
    { element: "tile_label_3", mandatory: false },
    { element: "tile_objection_4", mandatory: false },
    { element: "tile_response_4", mandatory: false },
    { element: "tile_label_4", mandatory: false },
    { element: "tile_objection_5", mandatory: false },
    { element: "tile_response_5", mandatory: false },
    { element: "tile_label_5", mandatory: false },
    { element: "tile_objection_6", mandatory: false },
    { element: "tile_response_6", mandatory: false },
    { element: "tile_label_6", mandatory: false },
    // Tile icons
    { element: "tile_icon_1", mandatory: false },
    { element: "tile_icon_2", mandatory: false },
    { element: "tile_icon_3", mandatory: false },
    { element: "tile_icon_4", mandatory: false },
    { element: "tile_icon_5", mandatory: false },
    { element: "tile_icon_6", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "objection_titles", mandatory: false },
    { element: "objection_responses", mandatory: false },
    { element: "tile_labels", mandatory: false },
  ],

  ProblemToReframeBlocks: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual problem/reframe pairs (up to 6 pairs)
    { element: "problem_1", mandatory: true },
    { element: "reframe_1", mandatory: true },
    { element: "problem_2", mandatory: true },
    { element: "reframe_2", mandatory: true },
    { element: "problem_3", mandatory: true },
    { element: "reframe_3", mandatory: true },
    { element: "problem_4", mandatory: false },
    { element: "reframe_4", mandatory: false },
    { element: "problem_5", mandatory: false },
    { element: "reframe_5", mandatory: false },
    { element: "problem_6", mandatory: false },
    { element: "reframe_6", mandatory: false },
    // Transition and styling
    { element: "transition_text", mandatory: false },
    { element: "problem_icon", mandatory: false },
    { element: "reframe_icon", mandatory: false },
    { element: "transition_icon", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "problem_statements", mandatory: false },
    { element: "reframe_statements", mandatory: false },
  ],

  SkepticToBelieverSteps: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual step progression fields (up to 5 steps)
    { element: "step_name_1", mandatory: true },
    { element: "step_quote_1", mandatory: true },
    { element: "step_result_1", mandatory: true },
    { element: "step_name_2", mandatory: true },
    { element: "step_quote_2", mandatory: true },
    { element: "step_result_2", mandatory: true },
    { element: "step_name_3", mandatory: true },
    { element: "step_quote_3", mandatory: true },
    { element: "step_result_3", mandatory: true },
    { element: "step_name_4", mandatory: false },
    { element: "step_quote_4", mandatory: false },
    { element: "step_result_4", mandatory: false },
    { element: "step_name_5", mandatory: false },
    { element: "step_quote_5", mandatory: false },
    { element: "step_result_5", mandatory: false },
    // Step icons
    { element: "step_icon_1", mandatory: false },
    { element: "step_icon_2", mandatory: false },
    { element: "step_icon_3", mandatory: false },
    { element: "step_icon_4", mandatory: false },
    { element: "step_icon_5", mandatory: false },
    { element: "step_icon_6", mandatory: false },
    // Summary and context
    { element: "objections_summary", mandatory: false },
    // Legacy field for backward compatibility
    { element: "conversion_steps", mandatory: false },
  ],

  BoldGuaranteePanel: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Guarantee structure
    { element: "guarantee_statement", mandatory: true },
    { element: "guarantee_details", mandatory: true },
    { element: "guarantee_period", mandatory: false },
    { element: "guarantee_conditions", mandatory: false },
    // Risk reversal elements
    { element: "risk_reversal_text", mandatory: false },
    { element: "refund_process", mandatory: false },
    { element: "no_questions_asked", mandatory: false },
    // Trust building elements
    { element: "trust_badges", mandatory: false },
    { element: "security_assurance", mandatory: false },
    { element: "company_backing", mandatory: false },
    // Visual elements
    { element: "guarantee_icon", mandatory: false },
    { element: "security_icon", mandatory: false },
    { element: "refund_icon", mandatory: false },
    { element: "shield_icon", mandatory: false },
  ],

  ObjectionCarousel: [
    { element: "headline", mandatory: true },
    { element: "subheadline", mandatory: false },
    // Individual carousel objection slides (up to 8 slides for carousel)
    { element: "slide_objection_1", mandatory: true },
    { element: "slide_response_1", mandatory: true },
    { element: "slide_objection_2", mandatory: true },
    { element: "slide_response_2", mandatory: true },
    { element: "slide_objection_3", mandatory: true },
    { element: "slide_response_3", mandatory: true },
    { element: "slide_objection_4", mandatory: false },
    { element: "slide_response_4", mandatory: false },
    { element: "slide_objection_5", mandatory: false },
    { element: "slide_response_5", mandatory: false },
    { element: "slide_objection_6", mandatory: false },
    { element: "slide_response_6", mandatory: false },
    { element: "slide_objection_7", mandatory: false },
    { element: "slide_response_7", mandatory: false },
    { element: "slide_objection_8", mandatory: false },
    { element: "slide_response_8", mandatory: false },
    // Carousel styling and navigation
    { element: "carousel_navigation", mandatory: false },
    { element: "slide_indicators", mandatory: false },
    { element: "auto_advance", mandatory: false },
    { element: "slide_duration", mandatory: false },
    // Slide icons
    { element: "slide_icon_1", mandatory: false },
    { element: "slide_icon_2", mandatory: false },
    { element: "slide_icon_3", mandatory: false },
    { element: "slide_icon_4", mandatory: false },
    { element: "slide_icon_5", mandatory: false },
    { element: "slide_icon_6", mandatory: false },
    { element: "slide_icon_7", mandatory: false },
    { element: "slide_icon_8", mandatory: false },
    // Legacy fields for backward compatibility
    { element: "objection_titles", mandatory: false },
    { element: "objection_responses", mandatory: false },
  ],

  // Pricing Section - Enhanced with complete field definitions for 5/5 completeness rating
  TierCards: [
    { element: "headline", mandatory: true },
    { element: "tier_names", mandatory: true },
    { element: "tier_prices", mandatory: true },
    { element: "tier_descriptions", mandatory: true },
    { element: "cta_texts", mandatory: true },
    { element: "feature_lists", mandatory: false },
    { element: "popular_labels", mandatory: false },
    { element: "tier_count", mandatory: false },
    // Individual tier features (up to 3 tiers, 8 features each)
    { element: "tier_1_feature_1", mandatory: false },
    { element: "tier_1_feature_2", mandatory: false },
    { element: "tier_1_feature_3", mandatory: false },
    { element: "tier_1_feature_4", mandatory: false },
    { element: "tier_1_feature_5", mandatory: false },
    { element: "tier_1_feature_6", mandatory: false },
    { element: "tier_1_feature_7", mandatory: false },
    { element: "tier_1_feature_8", mandatory: false },
    { element: "tier_2_feature_1", mandatory: false },
    { element: "tier_2_feature_2", mandatory: false },
    { element: "tier_2_feature_3", mandatory: false },
    { element: "tier_2_feature_4", mandatory: false },
    { element: "tier_2_feature_5", mandatory: false },
    { element: "tier_2_feature_6", mandatory: false },
    { element: "tier_2_feature_7", mandatory: false },
    { element: "tier_2_feature_8", mandatory: false },
    { element: "tier_3_feature_1", mandatory: false },
    { element: "tier_3_feature_2", mandatory: false },
    { element: "tier_3_feature_3", mandatory: false },
    { element: "tier_3_feature_4", mandatory: false },
    { element: "tier_3_feature_5", mandatory: false },
    { element: "tier_3_feature_6", mandatory: false },
    { element: "tier_3_feature_7", mandatory: false },
    { element: "tier_3_feature_8", mandatory: false },
    // Trust indicators
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "show_trust_footer", mandatory: false },
  ],

  ToggleableMonthlyYearly: [
    { element: "headline", mandatory: true },
    { element: "tier_names", mandatory: true },
    { element: "monthly_prices", mandatory: true },
    { element: "yearly_prices", mandatory: true },
    { element: "tier_descriptions", mandatory: true },
    { element: "cta_texts", mandatory: true },
    { element: "feature_lists", mandatory: false },
    { element: "popular_tiers", mandatory: false },
    { element: "annual_discount_label", mandatory: false },
    { element: "billing_note", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    // Platform features section
    { element: "platform_features_title", mandatory: false },
    { element: "platform_feature_1_title", mandatory: false },
    { element: "platform_feature_1_desc", mandatory: false },
    { element: "platform_feature_1_icon", mandatory: false },
    { element: "platform_feature_2_title", mandatory: false },
    { element: "platform_feature_2_desc", mandatory: false },
    { element: "platform_feature_2_icon", mandatory: false },
    { element: "platform_feature_3_title", mandatory: false },
    { element: "platform_feature_3_desc", mandatory: false },
    { element: "platform_feature_3_icon", mandatory: false },
    { element: "platform_feature_4_title", mandatory: false },
    { element: "platform_feature_4_desc", mandatory: false },
    { element: "platform_feature_4_icon", mandatory: false },
    { element: "show_platform_features", mandatory: false },
  ],

  FeatureMatrix: [
    { element: "headline", mandatory: true },
    { element: "tier_names", mandatory: true },
    { element: "tier_prices", mandatory: true },
    { element: "tier_descriptions", mandatory: true },
    { element: "cta_texts", mandatory: true },
    { element: "feature_categories", mandatory: true },
    { element: "feature_names", mandatory: true },
    { element: "feature_availability", mandatory: true },
    { element: "popular_tiers", mandatory: false },
    { element: "feature_descriptions", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    // Enterprise features section
    { element: "enterprise_section_title", mandatory: false },
    { element: "enterprise_feature_1_title", mandatory: false },
    { element: "enterprise_feature_1_desc", mandatory: false },
    { element: "enterprise_feature_1_icon", mandatory: false },
    { element: "enterprise_feature_2_title", mandatory: false },
    { element: "enterprise_feature_2_desc", mandatory: false },
    { element: "enterprise_feature_2_icon", mandatory: false },
    { element: "enterprise_feature_3_title", mandatory: false },
    { element: "enterprise_feature_3_desc", mandatory: false },
    { element: "enterprise_feature_3_icon", mandatory: false },
    { element: "enterprise_feature_4_title", mandatory: false },
    { element: "enterprise_feature_4_desc", mandatory: false },
    { element: "enterprise_feature_4_icon", mandatory: false },
    { element: "show_enterprise_features", mandatory: false },
  ],

  SegmentBasedPricing: [
    { element: "headline", mandatory: true },
    { element: "segment_names", mandatory: true },
    { element: "segment_descriptions", mandatory: true },
    { element: "segment_use_cases", mandatory: true },
    { element: "tier_names", mandatory: true },
    { element: "tier_prices", mandatory: true },
    { element: "tier_features", mandatory: true },
    { element: "cta_texts", mandatory: true },
    { element: "recommended_tiers", mandatory: false },
    { element: "segment_icons", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    // Segment comparison section
    { element: "segment_comparison_title", mandatory: false },
    { element: "segment_comparison_desc", mandatory: false },
    { element: "show_segment_comparison", mandatory: false },
  ],

  SliderPricing: [
    { element: "headline", mandatory: true },
    { element: "pricing_type", mandatory: true },
    { element: "base_price", mandatory: true },
    { element: "unit_price", mandatory: true },
    { element: "min_units", mandatory: true },
    { element: "max_units", mandatory: true },
    { element: "default_units", mandatory: true },
    { element: "unit_label", mandatory: true },
    { element: "included_features", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "tier_breakpoints", mandatory: false },
    { element: "tier_discounts", mandatory: false },
    { element: "pricing_note", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
  ],

  CallToQuotePlan: [
    { element: "headline", mandatory: true },
    { element: "value_proposition", mandatory: true },
    { element: "contact_options", mandatory: true },
    { element: "contact_ctas", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    // Contact icons
    { element: "contact_icon_1", mandatory: false },
    { element: "contact_icon_2", mandatory: false },
    { element: "contact_icon_3", mandatory: false },
    { element: "contact_icon_4", mandatory: false },
  ],

  CardWithTestimonial: [
    { element: "headline", mandatory: true },
    { element: "tier_names", mandatory: true },
    { element: "tier_prices", mandatory: true },
    { element: "tier_descriptions", mandatory: true },
    { element: "cta_texts", mandatory: true },
    { element: "feature_lists", mandatory: false },
    { element: "popular_tiers", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    // Testimonial section
    { element: "testimonial_quote", mandatory: false },
    { element: "testimonial_name", mandatory: false },
    { element: "testimonial_title", mandatory: false },
    { element: "testimonial_company", mandatory: false },
    { element: "testimonial_avatar", mandatory: false },
    { element: "testimonial_rating", mandatory: false },
    // Social proof metrics
    { element: "social_metric_1", mandatory: false },
    { element: "social_metric_1_label", mandatory: false },
    { element: "social_metric_2", mandatory: false },
    { element: "social_metric_2_label", mandatory: false },
    { element: "social_metric_3", mandatory: false },
    { element: "social_metric_3_label", mandatory: false },
    { element: "social_metric_4", mandatory: false },
    { element: "social_metric_4_label", mandatory: false },
    // Guarantee section
    { element: "guarantee_title", mandatory: false },
    { element: "guarantee_description", mandatory: false },
    { element: "guarantee_period", mandatory: false },
    { element: "guarantee_icon", mandatory: false },
    { element: "show_guarantee", mandatory: false },
    // Social proof section
    { element: "social_proof_title", mandatory: false },
    { element: "show_social_proof", mandatory: false },
  ],

  MiniStackedCards: [
    { element: "headline", mandatory: true },
    { element: "tier_names", mandatory: true },
    { element: "tier_prices", mandatory: true },
    { element: "tier_descriptions", mandatory: true },
    { element: "cta_texts", mandatory: true },
    { element: "feature_lists", mandatory: false },
    { element: "popular_tiers", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    // FAQ section (up to 4 pairs)
    { element: "faq_question_1", mandatory: false },
    { element: "faq_answer_1", mandatory: false },
    { element: "faq_question_2", mandatory: false },
    { element: "faq_answer_2", mandatory: false },
    { element: "faq_question_3", mandatory: false },
    { element: "faq_answer_3", mandatory: false },
    { element: "faq_question_4", mandatory: false },
    { element: "faq_answer_4", mandatory: false },
    { element: "faq_section_title", mandatory: false },
    { element: "show_faq", mandatory: false },
    // Plans features section (up to 3 features)
    { element: "plans_feature_1_title", mandatory: false },
    { element: "plans_feature_1_desc", mandatory: false },
    { element: "plans_feature_1_icon", mandatory: false },
    { element: "plans_feature_2_title", mandatory: false },
    { element: "plans_feature_2_desc", mandatory: false },
    { element: "plans_feature_2_icon", mandatory: false },
    { element: "plans_feature_3_title", mandatory: false },
    { element: "plans_feature_3_desc", mandatory: false },
    { element: "plans_feature_3_icon", mandatory: false },
    { element: "plans_features_title", mandatory: false },
    { element: "show_plans_features", mandatory: false },
    // Trust indicators (up to 4)
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "show_trust_item_1", mandatory: false },
    { element: "show_trust_item_2", mandatory: false },
    { element: "show_trust_item_3", mandatory: false },
    { element: "show_trust_item_4", mandatory: false },
  ],

  // PrimaryCTA Section - Enhanced with complete field definitions
  CenteredHeadlineCTA: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "urgency_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "customer_count", mandatory: false },
    { element: "customer_label", mandatory: false },
    { element: "rating_stat", mandatory: false },
    { element: "uptime_stat", mandatory: false },
    { element: "uptime_label", mandatory: false },
  ],

  CTAWithBadgeRow: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "trust_badges", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "customer_count", mandatory: false },
    { element: "rating_value", mandatory: false },
    { element: "rating_count", mandatory: false },
    { element: "show_social_proof", mandatory: false },
    { element: "show_customer_avatars", mandatory: false },
    { element: "avatar_count", mandatory: false },
    { element: "customer_names", mandatory: false },
    { element: "avatar_urls", mandatory: false },
  ],

  VisualCTAWithMockup: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "secondary_cta", mandatory: false },
    { element: "mockup_image", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
  ],

  SideBySideCTA: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "value_proposition", mandatory: true },
    { element: "benefit_list", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
  ],

  CountdownLimitedCTA: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "countdown_label", mandatory: true },
    { element: "scarcity_text", mandatory: true },
    { element: "urgency_text", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "countdown_end_date", mandatory: false },
    { element: "countdown_end_time", mandatory: false },
    { element: "limited_quantity", mandatory: false },
    { element: "availability_text", mandatory: false },
    { element: "bonus_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
  ],

  CTAWithFormField: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "form_label", mandatory: true },
    { element: "placeholder_text", mandatory: true },
    { element: "privacy_text", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "benefits", mandatory: false },
    { element: "benefit_1", mandatory: false },
    { element: "benefit_2", mandatory: false },
    { element: "benefit_3", mandatory: false },
    { element: "benefit_4", mandatory: false },
    { element: "benefit_5", mandatory: false },
    { element: "trust_item_1", mandatory: false },
    { element: "trust_item_2", mandatory: false },
    { element: "trust_item_3", mandatory: false },
    { element: "trust_item_4", mandatory: false },
    { element: "trust_item_5", mandatory: false },
    { element: "form_type", mandatory: false },
    { element: "required_fields", mandatory: false },
    { element: "success_message", mandatory: false },
  ],

  ValueStackCTA: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "value_propositions", mandatory: true },
    { element: "value_descriptions", mandatory: true },
    { element: "final_cta_headline", mandatory: true },
    { element: "final_cta_description", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "guarantee_text", mandatory: false },
    { element: "value_icon_1", mandatory: false },
    { element: "value_icon_2", mandatory: false },
    { element: "value_icon_3", mandatory: false },
    { element: "value_icon_4", mandatory: false },
    { element: "value_icon_5", mandatory: false },
    { element: "value_icon_6", mandatory: false },
  ],

  TestimonialCTACombo: [
    { element: "headline", mandatory: true },
    { element: "cta_text", mandatory: true },
    { element: "testimonial_quote", mandatory: true },
    { element: "testimonial_author", mandatory: true },
    { element: "testimonial_title", mandatory: true },
    { element: "testimonial_company", mandatory: true },
    { element: "subheadline", mandatory: false },
    { element: "testimonial_company_logo", mandatory: false },
    { element: "testimonial_date", mandatory: false },
    { element: "testimonial_industry", mandatory: false },
    { element: "case_study_tag", mandatory: false },
    { element: "customer_count", mandatory: false },
    { element: "average_rating", mandatory: false },
    { element: "uptime_percentage", mandatory: false },
    { element: "show_social_proof", mandatory: false },
  ],

  // Problem Section
  StackedPainBullets: [
    { element: "headline", mandatory: true },
    { element: "pain_points", mandatory: true },
    { element: "pain_descriptions", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "conclusion_text", mandatory: false },
    { element: "pain_icon_1", mandatory: false },
    { element: "pain_icon_2", mandatory: false },
    { element: "pain_icon_3", mandatory: false },
    { element: "pain_icon_4", mandatory: false },
    { element: "pain_icon_5", mandatory: false },
    { element: "pain_icon_6", mandatory: false },
  ],

  BeforeImageAfterText: [
    { element: "headline", mandatory: true },
    { element: "before_description", mandatory: true },
    { element: "after_description", mandatory: true },
    { element: "before_after_image", mandatory: false },
    { element: "image_caption", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "transformation_icon_1", mandatory: false },
    { element: "transformation_icon_2", mandatory: false },
    { element: "transformation_icon_3", mandatory: false },
  ],

  SideBySideSplit: [
    { element: "headline", mandatory: true },
    { element: "problem_title", mandatory: true },
    { element: "problem_description", mandatory: true },
    { element: "solution_preview", mandatory: true },
    { element: "problem_points", mandatory: false },
    { element: "solution_points", mandatory: false },
    { element: "call_to_action", mandatory: false },
    { element: "transition_text", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "bottom_stat_1", mandatory: false },
    { element: "bottom_stat_1_label", mandatory: false },
    { element: "bottom_stat_2", mandatory: false },
    { element: "bottom_stat_2_label", mandatory: false },
    { element: "bottom_stat_3", mandatory: false },
    { element: "bottom_stat_3_label", mandatory: false },
    { element: "cta_section_message", mandatory: false },
    { element: "path_1_icon", mandatory: false },
    { element: "path_2_icon", mandatory: false },
  ],

  EmotionalQuotes: [
    { element: "headline", mandatory: true },
    { element: "emotional_quotes", mandatory: true },
    { element: "quote_attributions", mandatory: true },
    { element: "context_text", mandatory: false },
    { element: "quote_categories", mandatory: false },
    { element: "emotional_impact", mandatory: false },
    { element: "relatable_intro", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "category_icon_1", mandatory: false },
    { element: "category_icon_2", mandatory: false },
    { element: "category_icon_3", mandatory: false },
    { element: "category_icon_4", mandatory: false },
    { element: "category_icon_5", mandatory: false },
  ],

  CollapsedCards: [
    { element: "headline", mandatory: true },
    { element: "problem_titles", mandatory: true },
    { element: "problem_descriptions", mandatory: true },
    { element: "expand_labels", mandatory: false },
    { element: "problem_impacts", mandatory: false },
    { element: "solution_hints", mandatory: false },
    { element: "intro_text", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "problem_icon_1", mandatory: false },
    { element: "problem_icon_2", mandatory: false },
    { element: "problem_icon_3", mandatory: false },
    { element: "problem_icon_4", mandatory: false },
    { element: "problem_icon_5", mandatory: false },
    { element: "problem_icon_6", mandatory: false },
  ],

  PainMeterChart: [
    { element: "headline", mandatory: true },
    { element: "pain_categories", mandatory: true },
    { element: "pain_levels", mandatory: true },
    { element: "chart_labels", mandatory: false },
    { element: "category_descriptions", mandatory: false },
    { element: "total_score_text", mandatory: false },
    { element: "benchmark_text", mandatory: false },
    { element: "intro_text", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "action_stat_1", mandatory: false },
    { element: "action_stat_1_label", mandatory: false },
    { element: "action_stat_2", mandatory: false },
    { element: "action_stat_2_label", mandatory: false },
    { element: "action_stat_3", mandatory: false },
    { element: "action_stat_3_label", mandatory: false },
  ],

  PersonaPanels: [
    { element: "headline", mandatory: true },
    { element: "persona_names", mandatory: true },
    { element: "persona_problems", mandatory: true },
    { element: "persona_descriptions", mandatory: false },
    { element: "persona_titles", mandatory: false },
    { element: "persona_pain_points", mandatory: false },
    { element: "persona_goals", mandatory: false },
    { element: "intro_text", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "persona_icon_1", mandatory: false },
    { element: "persona_icon_2", mandatory: false },
    { element: "persona_icon_3", mandatory: false },
    { element: "persona_icon_4", mandatory: false },
  ],

  ProblemChecklist: [
    { element: "headline", mandatory: true },
    { element: "problem_statements", mandatory: true },
    { element: "checklist_items", mandatory: true },
    { element: "conclusion_text", mandatory: false },
    { element: "scoring_labels", mandatory: false },
    { element: "action_thresholds", mandatory: false },
    { element: "intro_text", mandatory: false },
    { element: "subheadline", mandatory: false },
    { element: "supporting_text", mandatory: false },
    { element: "cta_text", mandatory: false },
    { element: "trust_items", mandatory: false },
    { element: "result_stat_1", mandatory: false },
    { element: "result_stat_1_label", mandatory: false },
    { element: "result_stat_2", mandatory: false },
    { element: "result_stat_2_label", mandatory: false },
    { element: "result_stat_3", mandatory: false },
    { element: "result_stat_3_label", mandatory: false },
    { element: "encouragement_tip_1", mandatory: false },
    { element: "encouragement_tip_2", mandatory: false },
    { element: "encouragement_tip_3", mandatory: false },
  ],

  // Header Section
  MinimalNavHeader: [
    { element: "nav_item_1", mandatory: true },
    { element: "nav_item_2", mandatory: false },
    { element: "nav_item_3", mandatory: false },
    { element: "nav_item_4", mandatory: false },
    { element: "nav_link_1", mandatory: false },
    { element: "nav_link_2", mandatory: false },
    { element: "nav_link_3", mandatory: false },
    { element: "nav_link_4", mandatory: false },
  ],

  NavWithCTAHeader: [
    { element: "nav_item_1", mandatory: true },
    { element: "nav_item_2", mandatory: false },
    { element: "nav_item_3", mandatory: false },
    { element: "nav_item_4", mandatory: false },
    { element: "nav_link_1", mandatory: false },
    { element: "nav_link_2", mandatory: false },
    { element: "nav_link_3", mandatory: false },
    { element: "nav_link_4", mandatory: false },
    { element: "cta_text", mandatory: true },
  ],

  CenteredLogoHeader: [
    { element: "nav_item_1", mandatory: true },
    { element: "nav_item_2", mandatory: true },
    { element: "nav_item_3", mandatory: false },
    { element: "nav_item_4", mandatory: false },
    { element: "nav_item_5", mandatory: false },
    { element: "nav_item_6", mandatory: false },
    { element: "nav_link_1", mandatory: false },
    { element: "nav_link_2", mandatory: false },
    { element: "nav_link_3", mandatory: false },
    { element: "nav_link_4", mandatory: false },
    { element: "nav_link_5", mandatory: false },
    { element: "nav_link_6", mandatory: false },
  ],

  FullNavHeader: [
    { element: "nav_item_1", mandatory: true },
    { element: "nav_item_2", mandatory: false },
    { element: "nav_item_3", mandatory: false },
    { element: "nav_item_4", mandatory: false },
    { element: "nav_item_5", mandatory: false },
    { element: "nav_link_1", mandatory: false },
    { element: "nav_link_2", mandatory: false },
    { element: "nav_link_3", mandatory: false },
    { element: "nav_link_4", mandatory: false },
    { element: "nav_link_5", mandatory: false },
    { element: "cta_text", mandatory: true },
    { element: "secondary_cta_text", mandatory: false },
  ],

  // Footer Section
  SimpleFooter: [
    { element: "copyright", mandatory: true },
    { element: "link_text_1", mandatory: false },
    { element: "link_1", mandatory: false },
    { element: "link_text_2", mandatory: false },
    { element: "link_2", mandatory: false },
    { element: "link_text_3", mandatory: false },
    { element: "link_3", mandatory: false },
  ],

  LinksAndSocialFooter: [
    { element: "copyright", mandatory: true },
    { element: "company_name", mandatory: false },
    { element: "tagline", mandatory: false },
    { element: "link_text_1", mandatory: false },
    { element: "link_1", mandatory: false },
    { element: "link_text_2", mandatory: false },
    { element: "link_2", mandatory: false },
    { element: "link_text_3", mandatory: false },
    { element: "link_3", mandatory: false },
    { element: "link_text_4", mandatory: false },
    { element: "link_4", mandatory: false },
    { element: "social_twitter", mandatory: false },
    { element: "social_linkedin", mandatory: false },
    { element: "social_github", mandatory: false },
    { element: "social_facebook", mandatory: false },
  ],

  MultiColumnFooter: [
    { element: "copyright", mandatory: true },
    { element: "company_description", mandatory: false },
    { element: "column_1_title", mandatory: false },
    { element: "column_1_link_text_1", mandatory: false },
    { element: "column_1_link_1", mandatory: false },
    { element: "column_1_link_text_2", mandatory: false },
    { element: "column_1_link_2", mandatory: false },
    { element: "column_1_link_text_3", mandatory: false },
    { element: "column_1_link_3", mandatory: false },
    { element: "column_1_link_text_4", mandatory: false },
    { element: "column_1_link_4", mandatory: false },
    { element: "column_2_title", mandatory: false },
    { element: "column_2_link_text_1", mandatory: false },
    { element: "column_2_link_1", mandatory: false },
    { element: "column_2_link_text_2", mandatory: false },
    { element: "column_2_link_2", mandatory: false },
    { element: "column_2_link_text_3", mandatory: false },
    { element: "column_2_link_3", mandatory: false },
    { element: "column_2_link_text_4", mandatory: false },
    { element: "column_2_link_4", mandatory: false },
    { element: "column_3_title", mandatory: false },
    { element: "column_3_link_text_1", mandatory: false },
    { element: "column_3_link_1", mandatory: false },
    { element: "column_3_link_text_2", mandatory: false },
    { element: "column_3_link_2", mandatory: false },
    { element: "column_3_link_text_3", mandatory: false },
    { element: "column_3_link_3", mandatory: false },
    { element: "column_3_link_text_4", mandatory: false },
    { element: "column_3_link_4", mandatory: false },
  ],

  ContactFooter: [
    { element: "copyright", mandatory: true },
    { element: "newsletter_title", mandatory: false },
    { element: "newsletter_description", mandatory: false },
    { element: "newsletter_cta", mandatory: false },
    { element: "email", mandatory: false },
    { element: "phone", mandatory: false },
    { element: "address", mandatory: false },
    { element: "link_text_1", mandatory: false },
    { element: "link_1", mandatory: false },
    { element: "link_text_2", mandatory: false },
    { element: "link_2", mandatory: false },
    { element: "link_text_3", mandatory: false },
    { element: "link_3", mandatory: false },
    { element: "link_text_4", mandatory: false },
    { element: "link_4", mandatory: false },
  ],
}