import React, { useEffect, useState } from 'react';
import { useLayoutComponent } from '@/hooks/useLayoutComponent';
import { useEditStoreLegacy as useEditStore } from '@/hooks/useEditStoreLegacy';
import { LayoutSection } from '@/components/layout/LayoutSection';
import { LayoutComponentProps } from '@/types/storeTypes';
import HeaderLogo from '@/components/ui/HeaderLogo';
import NavigationEditor from '@/components/navigation/NavigationEditor';
import type { NavigationItem } from '@/types/store/state';
import { logger } from '@/lib/logger';

// V2 Schema - nav_items array format
interface NavItem {
  id: string;
  label: string;
  link: string;
}

interface MinimalNavHeaderContent {
  nav_items?: NavItem[];
}

// Content schema - V2 format with nav_items collection
const CONTENT_SCHEMA = {
  // Navigation managed via store.navigationConfig, no section-level defaults needed
};

const MinimalNavHeader: React.FC<LayoutComponentProps> = (props) => {
  const {
    sectionId,
    mode,
    blockContent,
    colorTokens,
    sectionBackground,
    backgroundType,
    handleContentUpdate
  } = useLayoutComponent<MinimalNavHeaderContent>({
    ...props,
    contentSchema: CONTENT_SCHEMA
  });
  const store = useEditStore();
  const [showNavigationEditor, setShowNavigationEditor] = useState(false);
  
  // Initialize navigation if not already done
  useEffect(() => {
    if (!store.navigationConfig) {
      store.initializeNavigation();
    }
  }, [store]);

  // Get navigation items from store (primary), fallback to V2 content or defaults
  const getNavItems = (): NavigationItem[] => {
    // Primary: store.navigationConfig
    if (store.navigationConfig?.items && store.navigationConfig.items.length > 0) {
      return store.navigationConfig.items.slice(0, 4); // Max 4 for MinimalNavHeader
    }

    // Fallback: V2 nav_items array from content
    if (blockContent.nav_items && blockContent.nav_items.length > 0) {
      return blockContent.nav_items.slice(0, 4).map((item, index) => ({
        id: item.id || `nav-${index + 1}`,
        label: item.label,
        link: item.link || '#',
        isAutoGenerated: false,
        order: index,
      }));
    }

    // Default items if nothing configured
    return [
      { id: 'nav-1', label: 'Home', link: '#', isAutoGenerated: true, order: 0 },
      { id: 'nav-2', label: 'Features', link: '#features', isAutoGenerated: true, order: 1 },
      { id: 'nav-3', label: 'Pricing', link: '#pricing', isAutoGenerated: true, order: 2 },
      { id: 'nav-4', label: 'Contact', link: '#contact', isAutoGenerated: true, order: 3 },
    ];
  };

  const navItems = getNavItems();

  const handleNavClick = (e: React.MouseEvent<HTMLAnchorElement>, link: string) => {
    e.preventDefault();
    e.stopPropagation();
    
    logger.dev('🧭 [NAV-DEBUG] MinimalNav click:', () => ({ link, mode }));
    
    // In edit mode, don't navigate - let text editing work
    if (mode !== 'preview') {
      return;
    }
    
    if (link.startsWith('#')) {
      const element = document.querySelector(link);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      } else {
      }
    } else {
      window.open(link, '_blank');
    }
  };


  return (
    <LayoutSection
      sectionId={sectionId}
      sectionType="MinimalNavHeader"
      backgroundType={backgroundType}
      sectionBackground={sectionBackground}
      mode={mode}
      className=""
      noPadding
    >
      <nav className="relative flex items-center justify-center py-3 md:py-4">
        {/* Logo - absolute left */}
        <div className="absolute left-0 flex items-center">
          <HeaderLogo
            mode={mode}
            className="h-8 md:h-10 w-auto object-contain"
          />
        </div>

        {/* Navigation - centered */}
        <div className="flex items-center gap-4">
          {mode === 'preview' ? (
            // Preview Mode: Simple clickable navigation
            <ul className="flex items-center gap-4 md:gap-5">
              {navItems.map((navItem, index) => (
                <li key={navItem.id}>
                  <a 
                    href={navItem.link}
                    className="text-sm font-medium transition-colors cursor-pointer"
                    style={{ color: colorTokens?.text || '#374151' }}
                    onClick={(e) => handleNavClick(e, navItem.link)}
                  >
                    {navItem.label || `Nav Item ${index + 1}`}
                  </a>
                </li>
              ))}
            </ul>
          ) : (
            // Edit Mode: Static display with edit button
            <>
              <div className="flex items-center gap-3 px-2 py-1 bg-blue-50 border border-blue-200 rounded">
                <span className="text-xs text-blue-700 font-medium">Nav:</span>
                <div className="flex gap-2">
                  {navItems.map((navItem, index) => (
                    <span key={navItem.id} className="text-xs text-blue-600">
                      {navItem.label || `Item ${index + 1}`}
                    </span>
                  ))}
                  {navItems.length === 0 && (
                    <span className="text-xs text-blue-500 italic">Auto</span>
                  )}
                </div>
              </div>
              
              <button
                onClick={() => setShowNavigationEditor(true)}
                className="p-1.5 bg-blue-600 text-white rounded text-xs font-medium hover:bg-blue-700 transition-colors"
                title="Edit navigation"
              >
                <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </button>
            </>
          )}
        </div>
      </nav>
      
      {/* Navigation Editor Modal */}
      <NavigationEditor
        isVisible={showNavigationEditor}
        onClose={() => setShowNavigationEditor(false)}
        targetHeaderId={sectionId}
      />
    </LayoutSection>
  );
};

export default MinimalNavHeader;