#!/usr/bin/env node
/**
 * coverageSummary.mjs — regenerate the human-readable coverage-100 summary.
 *
 *   node scripts/coverageSummary.mjs
 *
 * Reads  docs/research/coverage-100/{analyzed/*.json, progress.json}
 * Writes docs/research/coverage-100/summary.md
 *
 * Derived, never hand-edited: rerun after every batch. The analyzed JSONs are
 * the source of truth. `findings.md` remains the separate, human-written
 * synthesis produced once all sites are done.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.join('docs', 'research', 'coverage-100');
const ANALYZED = path.join(ROOT, 'analyzed');
const OUT = path.join(ROOT, 'summary.md');

// Raw analyzer capability name -> canonical slug (see proposed-capabilities.md).
// Collapses synonyms so the frequency count reflects concepts, not labels.
const CAP_ALIAS = {
  'affiliate-list': 'affiliate-hub',
  'affiliate-resource-directory': 'affiliate-hub',
  'content-feed': 'content-index',
  'recipe-index': 'content-index',
  'recipe-index / content-category-grid': 'content-index',
  'content-category-grid': 'content-index',
  'email-capture-popup': 'external-list-signup',
  'email-capture-popup / external-list-signup': 'external-list-signup',
  'podcast/media-hub': 'media-hub',
  'bibliography': 'works-catalog',
  'works-listing': 'works-catalog',
  'bibliography/works-listing': 'works-catalog',
};
const canon = n => CAP_ALIAS[n] ?? CAP_ALIAS[n?.trim?.()] ?? n;
const capName = c => canon(typeof c === 'string' ? c : c?.name ?? String(c));
const esc = s => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
const yn = v => (v === true ? 'yes' : v === false ? '**no**' : '?');

const progress = fs.existsSync(path.join(ROOT, 'progress.json'))
  ? JSON.parse(fs.readFileSync(path.join(ROOT, 'progress.json'), 'utf8'))
  : {};

const sites = fs
  .readdirSync(ANALYZED)
  .filter(f => f.endsWith('.json'))
  .map(f => ({ slug: f.replace(/\.json$/, ''), ...JSON.parse(fs.readFileSync(path.join(ANALYZED, f), 'utf8')) }))
  .sort((a, b) => a.slug.localeCompare(b.slug));

// ---- tallies -------------------------------------------------------------
const tally = (arr, key) => arr.reduce((m, x) => ((m[key(x)] = (m[key(x)] || 0) + 1), m), {});
const byCount = o => Object.entries(o).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));

const engines = tally(sites, s => s.engine?.pick ?? 'unknown');
const styles = tally(sites, s => s.design_style?.pick ?? 'unknown');
const kinds = tally(sites, s => s.structure?.kind ?? 'unknown');

const capSites = {}; // capability -> [slugs]
for (const s of sites) for (const c of s.capabilities?.proposed_new ?? []) (capSites[capName(c)] ??= []).push(s.slug);

const needed = {};
for (const s of sites) for (const c of s.capabilities?.needed ?? []) needed[capName(c)] = (needed[capName(c)] || 0) + 1;

const outOfIcp = sites.filter(s => s.in_icp === false);
const lowConf = sites.filter(s => (s.confidence?.level ?? '') !== 'high');
const statuses = tally(Object.values(progress), p => p.status ?? 'unknown');

// ---- render --------------------------------------------------------------
const L = [];
L.push('# coverage-100 — running summary');
L.push('');
L.push('> Auto-generated by `node scripts/coverageSummary.mjs` from `analyzed/*.json`.');
L.push('> Do not hand-edit — rerun it. Final synthesis lives in `findings.md`.');
L.push('');
L.push(`**${sites.length} of 100 sites analyzed.** ` + byCount(statuses).map(([k, v]) => `${v} ${k}`).join(' · '));
L.push('');

L.push('## Sites');
L.push('');
L.push('| # | slug | engine | in ICP | structure | conf | design style | one action |');
L.push('|---|------|--------|--------|-----------|------|--------------|------------|');
sites.forEach((s, i) =>
  L.push(
    `| ${i + 1} | \`${s.slug}\` | ${esc(s.engine?.pick)} | ${yn(s.in_icp)} | ${esc(s.structure?.kind)} (${s.structure?.page_count ?? '?'}) | ` +
      `${esc(s.confidence?.level)} | ${esc(s.design_style?.pick)} | ${esc(s.goal?.one_action)} |`
  )
);
L.push('');

L.push('## Distributions');
L.push('');
L.push(`- **Engine:** ${byCount(engines).map(([k, v]) => `${k} ${v}`).join(' · ')}`);
L.push(`- **Structure:** ${byCount(kinds).map(([k, v]) => `${k} ${v}`).join(' · ')}`);
L.push(`- **Design style:** ${byCount(styles).map(([k, v]) => `${k} ${v}`).join(' · ')}`);
L.push(`- **In ICP:** ${sites.filter(s => s.in_icp === true).length} yes · ${outOfIcp.length} no`);
L.push('');

L.push('## Proposed new capabilities');
L.push('');
L.push('The live signal. A capability seen once is an anecdote; the count is what matters.');
L.push('');
if (!Object.keys(capSites).length) L.push('_none yet_');
else {
  L.push('| capability | n | seen on |');
  L.push('|------------|---|---------|');
  for (const [c, slugs] of Object.entries(capSites).sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0])))
    L.push(`| \`${esc(c)}\` | ${slugs.length} | ${slugs.map(s => `\`${s}\``).join(', ')} |`);
}
L.push('');

L.push('## Existing capabilities exercised');
L.push('');
L.push(byCount(needed).map(([k, v]) => `\`${k}\` ×${v}`).join(' · ') || '_none yet_');
L.push('');

L.push('## Unmapped sections');
L.push('');
L.push('Observations the canonical section list could not express, recorded rather than forced to fit.');
L.push('');
let any = false;
for (const s of sites)
  for (const u of s.sections?.unmapped ?? []) {
    any = true;
    L.push(`- **\`${s.slug}\`** — ${esc(u.observed)}`);
    if (u.why_no_fit) L.push(`  - _why no fit:_ ${esc(u.why_no_fit)}`);
    if (u.closest) L.push(`  - _closest:_ \`${esc(u.closest)}\``);
  }
if (!any) L.push('_none yet_');
L.push('');

L.push('## Out-of-ICP sites (flagged, not dropped)');
L.push('');
L.push('Kept in the corpus. Excluded from no matrix without an explicit decision.');
L.push('');
if (!outOfIcp.length) L.push('_none_');
else for (const s of outOfIcp) L.push(`- **\`${s.slug}\`** — ${esc(s.business?.type_label)}. ${esc(s.engine?.ladder_reasoning).slice(0, 180)}`);
L.push('');

L.push('## Confidence caveats');
L.push('');
if (!lowConf.length) L.push('_all sites high-confidence_');
else for (const s of lowConf) L.push(`- **\`${s.slug}\`** (${esc(s.confidence?.level)}) — ${esc(s.confidence?.why)}`);
L.push('');

L.push('## Gap findings (verbatim)');
L.push('');
for (const s of sites) {
  if (!(s.gap_findings ?? []).length) continue;
  L.push(`### \`${s.slug}\``);
  for (const g of s.gap_findings) L.push(`- ${esc(g)}`);
  L.push('');
}

fs.writeFileSync(OUT, L.join('\n'));
console.log(`wrote ${OUT} — ${sites.length} sites, ${Object.keys(capSites).length} proposed capabilities, ${outOfIcp.length} out-of-ICP`);
